// apps/langseth3d_unstr_bench.cpp — Langseth & LeVeque (2000, JCP 165, §3.2) SPHERICAL
// RIEMANN PROBLEM between two parallel reflecting walls, on a GENUINE UNSTRUCTURED 3D
// mesh (GAUSS-THINC). Quarter domain [0,1.5]x[0,1.5]x[0,1]; mesh from .umsh (N3_MESH).
// IC: gas at rest, rho=1,p=1 everywhere EXCEPT inside a sphere centered (0,0,0.4) r=0.2
// where rho=1,p=5 (gamma=1.4). BC: x=0,y=0 = symmetry planes; z=0,z=1 = reflecting walls
// (all kind 1); x=1.5,y=1.5 = transmissive (kind 0). Main comparison time t=0.7.
// IC by cell centroid (mesh-agnostic). Env: N3_MESH(req), N3_T(0.7), N3_CFL(0.4),
// N3_FLUX(RHLLC), N3_VTK, N3_CSV. Intermediate dumps: N3_T1 (single mid dump) or
// N3_TDUMPS="0.5,0.7,0.8" (comma-list, one run, VTK per time). GAUSS via THINCQQ_GAUSS=1.
#include "cfd/mesh_unstructured3d.hpp"
#include "cfd/euler3d.hpp"
#include "cfd/solver_euler3d.hpp"
#include "cfd/reconstruct3d_o2_unstr.hpp"
#include "cfd/io_vtk.hpp"
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>
#include <string>
#include <algorithm>
#include <chrono>

using namespace cfd;

int main() {
    Euler3D eq; eq.gamma = 1.4;
    const char* mp = std::getenv("N3_MESH");
    if (!mp) { std::fprintf(stderr, "set N3_MESH=<file.umsh on domain [1.5,1.5,1]>\n"); return 1; }
    bool ok=false; Mesh m = load_umsh_3d(mp, &ok);
    if (!ok) { std::fprintf(stderr, "cannot load mesh %s\n", mp); return 1; }
    const int N = m.n_cells();
    // LANG_CASE=vortex => Langseth-LeVeque §3.3 "Vorticity Generated by a Shock Wave" (two perpendicular
    // cylinders, domain [1.5,1,0.5], all-symmetry inner BC, frames t=0.1/0.3/0.5). Default => §3.2 sphere.
    const bool vortex = std::getenv("LANG_CASE") && std::string(std::getenv("LANG_CASE"))=="vortex";
    const double Lx=1.5, Ly=vortex?1.0:1.5, Lz=vortex?0.5:1.0;
    const double T   = std::getenv("N3_T")   ? std::atof(std::getenv("N3_T"))   : (vortex?0.5:0.7);
    const double cfl = std::getenv("N3_CFL") ? std::atof(std::getenv("N3_CFL")) : 0.4;

    // IC. §3.2 sphere: rho=1,p=1 except sphere @(0,0,0.4) r=0.2 -> p=5.  §3.3 vortex (two cyls r=0.2):
    //   cyl1 axis z @ x=y=0 -> p=10 (overpressure -> cyl shock); cyl2 axis y @ x=0.4,z=0 -> rho=0.1 (low density
    //   contact; the shock hits it -> baroclinic vorticity -> 2 rolls). gamma=1.4. cyls do not overlap.
    std::vector<double> U0((size_t)5*N);
    for (int c=0;c<N;++c){ double x=m.cell_centers[3*c],y=m.cell_centers[3*c+1],z=m.cell_centers[3*c+2];
        double rho=1.0,p=1.0;
        if (vortex) {
            if (std::sqrt(x*x+y*y)<0.2)                    { rho=1.0; p=10.0; }  // cyl1 (z-axis) overpressure
            double dx=x-0.4; if (std::sqrt(dx*dx+z*z)<0.2) { rho=0.1; p=1.0;  }  // cyl2 (y-axis) low density
        } else {
            double dz=z-0.4;
            if (std::sqrt(x*x+y*y+dz*dz)<0.2)              { rho=1.0; p=5.0;  }  // sphere
        }
        double W[5]={rho,0,0,0,p},Uc[5]; eq.prim_to_cons(W,Uc);
        for(int v=0;v<5;++v) U0[(size_t)v*N+c]=Uc[v]; }

    // BC tags on boundary faces by location. tag: 1=x0 2=xL 3=y0 4=yL 5=z0 6=zL.
    // §3.2 sphere: x=0,y=0 symmetry; z=0,z=Lz reflecting walls; x=Lx,y=Ly transmissive.
    // §3.3 vortex: x=0,y=0,z=0 ALL symmetry planes; x=Lx,y=Ly,z=Lz transmissive.
    for (int f=0; f<m.n_faces(); ++f){ if(m.face_neighbour[f]>=0) continue;
        double fx=m.face_centers[3*f],fy=m.face_centers[3*f+1],fz=m.face_centers[3*f+2]; int tag=2;
        if(fx<1e-6)tag=1; else if(fx>Lx-1e-6)tag=2; else if(fy<1e-6)tag=3; else if(fy>Ly-1e-6)tag=4;
        else if(fz<1e-6)tag=5; else if(fz>Lz-1e-6)tag=6; m.face_bc_tag[f]=(int8_t)tag; }
    std::vector<BC3D> bcs(7);
    if (vortex) {
        bcs[1].kind=1; bcs[3].kind=1; bcs[5].kind=1;    // x=0,y=0,z=0 symmetry planes (slip)
        bcs[2].kind=0; bcs[4].kind=0; bcs[6].kind=0;    // x=Lx,y=Ly,z=Lz transmissive outer
    } else {
        bcs[1].kind=1; bcs[3].kind=1;                   // x=0,y=0 symmetry planes (slip)
        bcs[5].kind=1; bcs[6].kind=1;                   // z=0,z=Lz reflecting walls (slip)
        bcs[2].kind=0; bcs[4].kind=0;                   // x=Lx,y=Ly transmissive outer
    }
    const int flux  = std::getenv("N3_FLUX")  ? std::atoi(std::getenv("N3_FLUX"))  : (int)FLUX3_RHLLC;
    // recon: default BVD (high-order THINC); N3_RECON=1 = MUSCL (BJ vertex), 0 = first-order.
    const int recon = std::getenv("N3_RECON") ? std::atoi(std::getenv("N3_RECON")) : (int)RECON3_BVD;
    const char* rname = (recon==RECON3_BJ_VERTEX)?"muscl":(recon==RECON3_FIRST)?"first":"bvd";
    // Intermediate dumps, two mechanisms:
    //   N3_T1 (e.g. 0.5) + N3_VTK_MID -> dump the state at t=T1, then continue to T.
    //   N3_TDUMPS="0.5,0.7,0.8" -> ONE run, dump VTK at EACH listed time (path = N3_VTK
    //     with "_t<time>" inserted before ".vtk"); runs to the largest time (overrides N3_T).
    const double T1 = std::getenv("N3_T1") ? std::atof(std::getenv("N3_T1")) : -1.0;
    const char* tdumps = std::getenv("N3_TDUMPS");
    // Build a per-dump VTK filename from N3_VTK by inserting "_t<time>" before ".vtk".
    auto dump_vtk_name = [&](double tt)->std::string{
        const char* base = std::getenv("N3_VTK"); if(!base) return std::string();
        std::string s(base); char suf[32]; std::snprintf(suf,sizeof suf,"_t%.4f",tt);
        size_t dot=s.rfind(".vtk");
        return (dot==std::string::npos) ? (s+suf+".vtk") : (s.substr(0,dot)+suf+".vtk");
    };

    ReconCtx3DO2 o2 = build_recon_ctx_3d_o2_unstr(m);   // built once (mesh-only)
    // finalize: compute prims + vorticity/enstrophy, print the summary line at absolute time tabs, dump VTK/CSV.
    auto finalize=[&](const std::vector<double>& U, double tabs, int nsteps, double wall, const char* vtk, const char* csv){
        std::vector<double> frho(N),fu(N),fv(N),fw(N),fp(N);
        double rmin=1e300,rmax=-1e300,pmin=1e300; bool finite=true;
        for(int c=0;c<N;++c){ double Uc[5],W[5]; for(int v=0;v<5;++v)Uc[v]=U[(size_t)v*N+c];
            if(!std::isfinite(Uc[0]))finite=false; eq.cons_to_prim(Uc,W);
            frho[c]=W[0];fu[c]=W[1];fv[c]=W[2];fw[c]=W[3];fp[c]=W[4];
            rmin=std::min(rmin,W[0]);rmax=std::max(rmax,W[0]);pmin=std::min(pmin,W[4]); }
        std::vector<double> Wp((size_t)5*N); for(int v=0;v<5;++v)for(int c=0;c<N;++c) Wp[(size_t)v*N+c]= v==0?frho[c]:v==1?fu[c]:v==2?fv[c]:v==3?fw[c]:fp[c];
        std::vector<double> gu,gv,gw; reconstruct3d_o2_coeffs(m,o2,Wp,5,1,gu); reconstruct3d_o2_coeffs(m,o2,Wp,5,2,gv); reconstruct3d_o2_coeffs(m,o2,Wp,5,3,gw);
        std::vector<double> fvort(N); double ens=0;
        for(int c=0;c<N;++c){ double ox=gw[9*c+1]-gv[9*c+2], oy=gu[9*c+2]-gw[9*c+0], oz=gv[9*c+0]-gu[9*c+1];
            double w2=ox*ox+oy*oy+oz*oz; fvort[c]=std::sqrt(w2); ens+=w2*m.cell_volumes[c]; }
        std::printf("LangsethUnstr recon=%s flux=%d%s mesh=%s cells=%d rho=[%.4f,%.4f] p_min=%.4f finite=%d "
                    "enstrophy=%.4f steps=%d t=%.4f wall=%.1fs%s\n",
                    rname, flux, std::getenv("THINCQQ_GAUSS")?"+GAUSS":"", mp, N, rmin,rmax,pmin,(int)finite,
                    ens, nsteps, tabs, wall, (pmin<=0||!finite)?"  [DIVERGED/neg-p]":"");
        std::vector<VtkField> flds={{"rho",frho.data()},{"u",fu.data()},{"v",fv.data()},{"w",fw.data()},{"p",fp.data()},{"vortmag",fvort.data()}};
        if(vtk){ write_vtk_unstructured(vtk,m,flds); std::printf("VTK saved: %s\n",vtk); }
        if(csv){ FILE* fh=std::fopen(csv,"w"); if(fh){   // y~0 roll slab
            std::fprintf(fh,"x,y,z,rho,u,v,w,p,vortmag\n");
            for(int c=0;c<N;++c){ double y=m.cell_centers[3*c+1]; if(y>0.12) continue;
                std::fprintf(fh,"%.6g,%.6g,%.6g,%.7g,%.7g,%.7g,%.7g,%.7g,%.7g\n",
                    m.cell_centers[3*c],y,m.cell_centers[3*c+2],frho[c],fu[c],fv[c],fw[c],fp[c],fvort[c]); }
            std::fclose(fh); std::printf("CSV saved: %s (y~0 slab)\n",csv); } }
    };

    auto t0=std::chrono::steady_clock::now();
    if(tdumps){   // N3_TDUMPS: one run, dump VTK at each listed time (no recompute)
        std::vector<double> ts; { std::string s(tdumps); size_t p=0;
            while(p<=s.size()){ size_t q=s.find(',',p);
                std::string tok = s.substr(p, q==std::string::npos ? std::string::npos : q-p);
                double v=std::atof(tok.c_str()); if(v>0.0) ts.push_back(v);
                if(q==std::string::npos) break; p=q+1; } }
        std::sort(ts.begin(),ts.end());
        std::vector<double> Ucur=U0; double tprev=0.0; int nstot=0;
        for(size_t i=0;i<ts.size();++i){ double dt=ts[i]-tprev; if(dt<=0.0) continue;
            Solve3DResult R = solve_euler3d(m, eq, Ucur, dt, 2, cfl, -1.0, 100000000, recon, nullptr, flux, &bcs, nullptr);
            double wall=std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();
            Ucur=R.U; nstot+=R.n_steps; tprev+=R.t;
            std::string vp=dump_vtk_name(ts[i]); bool last=(i+1==ts.size());
            finalize(Ucur, tprev, nstot, wall, vp.empty()?nullptr:vp.c_str(), last?std::getenv("N3_CSV"):nullptr); }
    } else if(T1>0.0 && T1<T){   // two segments: 0->T1 (dump mid), T1->T (dump final)
        Solve3DResult R1 = solve_euler3d(m, eq, U0, T1, 2, cfl, -1.0, 100000000, recon, nullptr, flux, &bcs, nullptr);
        double w1 = std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();
        finalize(R1.U, R1.t, R1.n_steps, w1, std::getenv("N3_VTK_MID"), nullptr);   // t=T1 state
        Solve3DResult R2 = solve_euler3d(m, eq, R1.U, T-T1, 2, cfl, -1.0, 100000000, recon, nullptr, flux, &bcs, nullptr);
        double w2 = std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();
        finalize(R2.U, T1+R2.t, R1.n_steps+R2.n_steps, w2, std::getenv("N3_VTK"), std::getenv("N3_CSV"));   // t=T state
    } else {
        Solve3DResult R = solve_euler3d(m, eq, U0, T, 2, cfl, -1.0, 100000000, recon, nullptr, flux, &bcs, nullptr);
        double wall = std::chrono::duration<double>(std::chrono::steady_clock::now()-t0).count();
        finalize(R.U, R.t, R.n_steps, wall, std::getenv("N3_VTK"), std::getenv("N3_CSV"));
    }
    return 0;
}
