// Cartesian 2-D/3-D five-equation HLLC + SSPRK3 field solver.
#pragma once
#include <array>
#include <cmath>
#include <vector>
#include "cfd/five_eq/primitive_nd.hpp"
#include "cfd/five_eq/nd_reconstruction.hpp"
#include "cfd/five_eq/sound_speed.hpp"
namespace cfd::five_eq {
template<int D> struct NDState { std::array<int,D> shape{}; std::vector<ConsND<D>> U; std::vector<PrimND<D>> W; };
template<int D> struct NDOptions { std::array<double,D> dx{}; std::array<NDBoundary,D> boundary{}; NDReconstruction<D> reconstruction{}; std::array<double,D> gravity{}; bool use_gravity=false; MixtureSoundSpeedKind mixture_sound_speed_kind=MixtureSoundSpeedKind::Kapila; };
template<int D> inline int nd_cells(const std::array<int,D>& s){int n=1;for(int x:s)n*=x;return n;}
// Storage follows NumPy/C row-major order: the last axis is contiguous.
template<int D> inline int nd_neighbour(int q,int axis,int dir,const std::array<int,D>& s){int stride=1;for(int d=axis+1;d<D;++d)stride*=s[d];int c=(q/stride)%s[axis];int nc=(c+dir+s[axis])%s[axis];return q+(nc-c)*stride;}
template<int D> inline double nd_sound(const PrimND<D>& w,const EOS&e1,const EOS&e2,MixtureSoundSpeedKind mixture_kind=MixtureSoundSpeedKind::Kapila){double r1=e1.density(w.p,w.T1),r2=e2.density(w.p,w.T2);double c1=phase_sound_speed_sq(e1,r1,w.T1),c2=phase_sound_speed_sq(e2,r2,w.T2);return std::sqrt(std::fmax(mixture_sound_speed_sq(w.alpha,r1,c1,r2,c2,mixture_kind),1e-30));}
template<int D> inline void nd_flux(const PrimND<D>& w,const ConsND<D>& u,int a,std::array<double,D+4>& f){double un=w.velocity[a];f[0]=u.m1*un;f[1]=u.m2*un;for(int d=0;d<D;++d)f[2+d]=u.momentum[d]*un+(d==a?w.p:0.);f[2+D]=(u.rhoE+w.p)*un;f[3+D]=w.alpha*un;}
template<int D> inline void nd_hllc(const PrimND<D>& L,const PrimND<D>& R,const EOS&e1,const EOS&e2,int a,std::array<double,D+4>& F,MixtureSoundSpeedKind mixture_kind=MixtureSoundSpeedKind::Kapila){auto UL=prim_to_cons_nd(L,e1,e2),UR=prim_to_cons_nd(R,e1,e2);std::array<double,D+4> FL,FR;nd_flux(L,UL,a,FL);nd_flux(R,UR,a,FR);double rL=UL.m1+UL.m2,rR=UR.m1+UR.m2,uL=L.velocity[a],uR=R.velocity[a],cL=nd_sound(L,e1,e2,mixture_kind),cR=nd_sound(R,e1,e2,mixture_kind),SL=std::min(uL-cL,uR-cR),SR=std::max(uL+cL,uR+cR),den=rL*(SL-uL)-rR*(SR-uR);if(std::fabs(den)<1e-30)den=den<0?-1e-30:1e-30;double SM=(R.p-L.p+rL*uL*(SL-uL)-rR*uR*(SR-uR))/den;
 auto star=[&](const PrimND<D>&w,const ConsND<D>&U,double r,double S,double un,double p){std::array<double,D+4>x{};double d=S-SM;if(std::fabs(d)<1e-30)d=d<0?-1e-30:1e-30;double fac=(S-un)/d,rs=r*fac;x[0]=U.m1*fac;x[1]=U.m2*fac;for(int j=0;j<D;++j)x[2+j]=rs*(j==a?SM:w.velocity[j]);x[2+D]=((S-un)*U.rhoE-p*un+(p+r*(S-un)*(SM-un))*SM)/d;x[3+D]=U.alpha*fac;return x;};auto USL=star(L,UL,rL,SL,uL,L.p),USR=star(R,UR,rR,SR,uR,R.p);for(int k=0;k<D+4;++k){if(0<=SL)F[k]=FL[k];else if(0<=SM)F[k]=FL[k]+SL*(USL[k]-(k==0?UL.m1:k==1?UL.m2:k<2+D?UL.momentum[k-2]:k==2+D?UL.rhoE:UL.alpha));else if(0<=SR)F[k]=FR[k]+SR*(USR[k]-(k==0?UR.m1:k==1?UR.m2:k<2+D?UR.momentum[k-2]:k==2+D?UR.rhoE:UR.alpha));else F[k]=FR[k];}}
template<int D> inline std::vector<ConsND<D>> nd_rhs(const NDState<D>& S,const EOS&e1,const EOS&e2,const std::array<double,D>& dx){int n=nd_cells<D>(S.shape);std::vector<ConsND<D>> R(n);for(int q=0;q<n;++q)for(int a=0;a<D;++a){int r=nd_neighbour<D>(q,a,1,S.shape);std::array<double,D+4>F;nd_hllc<D>(S.W[q],S.W[r],e1,e2,a,F);auto add=[&](ConsND<D>&x,double z){x.m1+=z*F[0];x.m2+=z*F[1];for(int j=0;j<D;++j)x.momentum[j]+=z*F[2+j];x.rhoE+=z*F[2+D];x.alpha+=z*F[3+D];};add(R[q],-1./dx[a]);add(R[r],1./dx[a]);}return R;}
template<int D> inline void nd_recover(NDState<D>&S,const EOS&e1,const EOS&e2){for(std::size_t i=0;i<S.U.size();++i)S.W[i]=cons_to_prim_nd(S.U[i],e1,e2,&S.W[i]);}
template<int D> inline void nd_step_ssprk3(NDState<D>&S,double dt,const EOS&e1,const EOS&e2,const std::array<double,D>&dx){auto U0=S.U;auto R=nd_rhs<D>(S,e1,e2,dx);for(size_t i=0;i<S.U.size();++i){S.U[i].m1+=dt*R[i].m1;S.U[i].m2+=dt*R[i].m2;for(int d=0;d<D;++d)S.U[i].momentum[d]+=dt*R[i].momentum[d];S.U[i].rhoE+=dt*R[i].rhoE;S.U[i].alpha+=dt*R[i].alpha;}nd_recover(S,e1,e2);R=nd_rhs<D>(S,e1,e2,dx);for(size_t i=0;i<S.U.size();++i){auto&u=S.U[i];u.m1=.75*U0[i].m1+.25*(u.m1+dt*R[i].m1);u.m2=.75*U0[i].m2+.25*(u.m2+dt*R[i].m2);for(int d=0;d<D;++d)u.momentum[d]=.75*U0[i].momentum[d]+.25*(u.momentum[d]+dt*R[i].momentum[d]);u.rhoE=.75*U0[i].rhoE+.25*(u.rhoE+dt*R[i].rhoE);u.alpha=.75*U0[i].alpha+.25*(u.alpha+dt*R[i].alpha);}nd_recover(S,e1,e2);R=nd_rhs<D>(S,e1,e2,dx);for(size_t i=0;i<S.U.size();++i){auto&u=S.U[i];u.m1=(U0[i].m1+2*(u.m1+dt*R[i].m1))/3.;u.m2=(U0[i].m2+2*(u.m2+dt*R[i].m2))/3.;for(int d=0;d<D;++d)u.momentum[d]=(U0[i].momentum[d]+2*(u.momentum[d]+dt*R[i].momentum[d]))/3.;u.rhoE=(U0[i].rhoE+2*(u.rhoE+dt*R[i].rhoE))/3.;u.alpha=(U0[i].alpha+2*(u.alpha+dt*R[i].alpha))/3.;}nd_recover(S,e1,e2);}
template<int D> inline void nd_add_flux(ConsND<D>&u,const std::array<double,D+4>&f,double scale){u.m1+=scale*f[0];u.m2+=scale*f[1];for(int j=0;j<D;++j)u.momentum[j]+=scale*f[2+j];u.rhoE+=scale*f[2+D];u.alpha+=scale*f[3+D];}
template<int D> inline std::vector<ConsND<D>> nd_rhs(const NDState<D>&S,const EOS&e1,const EOS&e2,const NDOptions<D>&opt){const int n=nd_cells<D>(S.shape);std::vector<ConsND<D>> R(n);for(int a=0;a<D;++a){const double inv_dx=1./opt.dx[a];for(int q=0;q<n;++q){const int coordinate=nd_row_major_coordinate<D>(q,S.shape)[a];std::array<double,D+4>F{};if(opt.boundary[a]==NDBoundary::Periodic){const auto face=nd_reconstruct_face<D>(S.W,S.shape,q,a,0,opt.boundary[a],opt.reconstruction);nd_hllc<D>(face[0],face[1],e1,e2,a,F,opt.mixture_sound_speed_kind);const int r=nd_neighbour<D>(q,a,1,S.shape);nd_add_flux(R[q],F,-inv_dx);nd_add_flux(R[r],F,inv_dx);continue;}if(coordinate==0){const auto face=nd_reconstruct_face<D>(S.W,S.shape,q,a,-1,opt.boundary[a],opt.reconstruction);nd_hllc<D>(face[0],face[1],e1,e2,a,F,opt.mixture_sound_speed_kind);nd_add_flux(R[q],F,inv_dx);}if(coordinate<S.shape[a]-1){const auto face=nd_reconstruct_face<D>(S.W,S.shape,q,a,0,opt.boundary[a],opt.reconstruction);nd_hllc<D>(face[0],face[1],e1,e2,a,F,opt.mixture_sound_speed_kind);const int r=nd_neighbour<D>(q,a,1,S.shape);nd_add_flux(R[q],F,-inv_dx);nd_add_flux(R[r],F,inv_dx);}if(coordinate==S.shape[a]-1){const auto face=nd_reconstruct_face<D>(S.W,S.shape,q,a,0,opt.boundary[a],opt.reconstruction);nd_hllc<D>(face[0],face[1],e1,e2,a,F,opt.mixture_sound_speed_kind);nd_add_flux(R[q],F,-inv_dx);}}}if(opt.use_gravity)for(int q=0;q<n;++q){const double rho=S.U[q].m1+S.U[q].m2;for(int a=0;a<D;++a){R[q].momentum[a]+=rho*opt.gravity[a];R[q].rhoE+=S.U[q].momentum[a]*opt.gravity[a];}}return R;}
template<int D> inline void nd_step_ssprk3(NDState<D>&S,double dt,const EOS&e1,const EOS&e2,const NDOptions<D>&opt){const auto U0=S.U;auto R=nd_rhs<D>(S,e1,e2,opt);for(size_t i=0;i<S.U.size();++i){S.U[i].m1+=dt*R[i].m1;S.U[i].m2+=dt*R[i].m2;for(int d=0;d<D;++d)S.U[i].momentum[d]+=dt*R[i].momentum[d];S.U[i].rhoE+=dt*R[i].rhoE;S.U[i].alpha+=dt*R[i].alpha;}nd_recover(S,e1,e2);R=nd_rhs<D>(S,e1,e2,opt);for(size_t i=0;i<S.U.size();++i){auto&u=S.U[i];u.m1=.75*U0[i].m1+.25*(u.m1+dt*R[i].m1);u.m2=.75*U0[i].m2+.25*(u.m2+dt*R[i].m2);for(int d=0;d<D;++d)u.momentum[d]=.75*U0[i].momentum[d]+.25*(u.momentum[d]+dt*R[i].momentum[d]);u.rhoE=.75*U0[i].rhoE+.25*(u.rhoE+dt*R[i].rhoE);u.alpha=.75*U0[i].alpha+.25*(u.alpha+dt*R[i].alpha);}nd_recover(S,e1,e2);R=nd_rhs<D>(S,e1,e2,opt);for(size_t i=0;i<S.U.size();++i){auto&u=S.U[i];u.m1=(U0[i].m1+2*(u.m1+dt*R[i].m1))/3.;u.m2=(U0[i].m2+2*(u.m2+dt*R[i].m2))/3.;for(int d=0;d<D;++d)u.momentum[d]=(U0[i].momentum[d]+2*(u.momentum[d]+dt*R[i].momentum[d]))/3.;u.rhoE=(U0[i].rhoE+2*(u.rhoE+dt*R[i].rhoE))/3.;u.alpha=(U0[i].alpha+2*(u.alpha+dt*R[i].alpha))/3.;}nd_recover(S,e1,e2);}
template<int D> struct NDRunInfo { int steps=0; double t_final=0.,dt_last=0.; };
template<int D> inline NDState<D> make_nd_state(const std::array<int,D>& shape,const std::vector<PrimND<D>>& W,const EOS&e1,const EOS&e2){NDState<D>S;S.shape=shape;S.W=W;S.U.resize(W.size());for(std::size_t i=0;i<W.size();++i)S.U[i]=prim_to_cons_nd(W[i],e1,e2);return S;}
template<int D> inline NDState<D> solve_nd(const std::array<int,D>&shape,const std::vector<PrimND<D>>& W0,double t_end,const EOS&e1,const EOS&e2,const NDOptions<D>&opt,double cfl=.35,double dt_fixed=-1.,NDRunInfo<D>*info=nullptr){NDState<D>S=make_nd_state<D>(shape,W0,e1,e2);double t=0.,last=0.;int steps=0;while(t<t_end-1.e-15){double speed=1.e-30;for(const auto&w:S.W){const double c=nd_sound<D>(w,e1,e2,opt.mixture_sound_speed_kind);for(double v:w.velocity)speed=std::fmax(speed,std::fabs(v)+c);}double h=opt.dx[0];for(double d:opt.dx)h=std::min(h,d);double dt=dt_fixed>0.?dt_fixed:cfl*h/speed;dt=std::min(dt,t_end-t);nd_step_ssprk3<D>(S,dt,e1,e2,opt);t+=dt;last=dt;++steps;}if(info)*info={steps,t,last};return S;}
template<int D> inline NDState<D> solve_nd_periodic(const std::array<int,D>&shape,const std::vector<PrimND<D>>& W0,const std::array<double,D>&dx,double t_end,const EOS&e1,const EOS&e2,double cfl=.35,double dt_fixed=-1.,NDRunInfo<D>*info=nullptr){NDState<D>S=make_nd_state<D>(shape,W0,e1,e2);double t=0.,last=0.;int steps=0;while(t<t_end-1.e-15){double speed=1.e-30;for(const auto&w:S.W){const double c=nd_sound<D>(w,e1,e2);for(double v:w.velocity)speed=std::fmax(speed,std::fabs(v)+c);}double h=dx[0];for(double d:dx)h=std::min(h,d);double dt=dt_fixed>0.?dt_fixed:cfl*h/speed;dt=std::min(dt,t_end-t);nd_step_ssprk3<D>(S,dt,e1,e2,dx);t+=dt;last=dt;++steps;}if(info)*info={steps,t,last};return S;}
inline NDState<2> solve_2d_periodic(const std::array<int,2>& shape,const std::vector<PrimND<2>>& W0,const std::array<double,2>& dx,double t_end,const EOS&e1,const EOS&e2,double cfl=.35,double dt_fixed=-1.,NDRunInfo<2>*info=nullptr){return solve_nd_periodic<2>(shape,W0,dx,t_end,e1,e2,cfl,dt_fixed,info);}
inline NDState<3> solve_3d_periodic(const std::array<int,3>& shape,const std::vector<PrimND<3>>& W0,const std::array<double,3>& dx,double t_end,const EOS&e1,const EOS&e2,double cfl=.35,double dt_fixed=-1.,NDRunInfo<3>*info=nullptr){return solve_nd_periodic<3>(shape,W0,dx,t_end,e1,e2,cfl,dt_fixed,info);}
// Public counterparts of main_2d.py::solve_2d and main_3d.py::solve_3d.
// Shape stays explicit because C++ receives a flattened vector rather than a
// NumPy tensor.
inline NDState<2> solve_2d(const std::array<int,2>& shape,const std::vector<PrimND<2>>& W0,double t_end,const EOS&e1,const EOS&e2,const NDOptions<2>&opt,double cfl=.35,double dt_fixed=-1.,NDRunInfo<2>*info=nullptr){return solve_nd<2>(shape,W0,t_end,e1,e2,opt,cfl,dt_fixed,info);}
inline NDState<3> solve_3d(const std::array<int,3>& shape,const std::vector<PrimND<3>>& W0,double t_end,const EOS&e1,const EOS&e2,const NDOptions<3>&opt,double cfl=.35,double dt_fixed=-1.,NDRunInfo<3>*info=nullptr){return solve_nd<3>(shape,W0,t_end,e1,e2,opt,cfl,dt_fixed,info);}
} // namespace cfd::five_eq
