const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel,
        TabStopType, TabStopPosition, Table, TableRow, TableCell, WidthType, BorderStyle } = require("docx");

const FONT = "Times New Roman";
const SZ = 20; // 10pt
const p = (t) => new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 120, line: 276 },
  children: [new TextRun({ text: t, font: FONT, size: SZ })] });
const runs = (arr) => new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 120, line: 276 },
  children: arr.map(r => new TextRun({ font: FONT, size: SZ, ...r })) });
const h1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 280, after: 160 },
  children: [new TextRun({ text: t, font: FONT, size: 22, bold: true })] });
const h2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 220, after: 120 },
  children: [new TextRun({ text: t, font: FONT, size: 20, bold: true, italics: true })] });
const eq = (t, n) => new Paragraph({
  alignment: AlignmentType.LEFT, spacing: { before: 100, after: 100 },
  tabStops: [{ type: TabStopType.CENTER, position: 4680 }, { type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
  children: [ new TextRun({ text: "\t", font: FONT, size: SZ }),
    new TextRun({ text: t, font: "Cambria Math", size: SZ, italics: true }),
    new TextRun({ text: "\t(" + n + ")", font: FONT, size: SZ }) ] });
const refP = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { after: 60 },
  indent: { left: 360, hanging: 360 },
  children: [new TextRun({ text: t, font: FONT, size: 18 })] });
// --- table/figure helpers (placeholder-valued tables + caption paragraphs) ---
const bd = { style: BorderStyle.SINGLE, size: 1, color: "888888" };
const borders = { top: bd, bottom: bd, left: bd, right: bd };
const cell = (t, w, b) => new TableCell({ borders, width: { size: w, type: WidthType.DXA },
  margins: { top: 60, bottom: 60, left: 100, right: 100 },
  children: [new Paragraph({ alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: t, font: FONT, size: 18, bold: !!b })] })] });
const mkTable = (widths, head, rows) => new Table({
  width: { size: widths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: widths,
  rows: [ new TableRow({ children: head.map((h, i) => cell(h, widths[i], true)) }),
          ...rows.map(r => new TableRow({ children: r.map((c, i) => cell(c, widths[i])) })) ] });
const tcap = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { before: 160, after: 80 },
  children: [new TextRun({ text: t, font: FONT, size: 18, italics: true })] });
const fcap = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { before: 120, after: 160 },
  children: [new TextRun({ text: t, font: FONT, size: 18, italics: true })] });

const C = [];

C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
  children: [new TextRun({ text: "A boundary-variation-diminishing adaptive TVD reconstruction with multi-dimensional vertex-monotone bounds as a low-dissipation candidate for BVD schemes on unstructured grids", font: FONT, size: 28, bold: true })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
  children: [new TextRun({ text: "Younglin Yoo", font: FONT, size: 22 })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 240 },
  children: [new TextRun({ text: "[Affiliation, address, e-mail]", font: FONT, size: 18, italics: true })] }));

// ================= Abstract =================
C.push(h1("Abstract"));
C.push(p("This paper develops a low-dissipation reconstruction scheme for the compressible Euler equations on two- and three-dimensional unstructured grids within the boundary-variation-diminishing (BVD) framework. The scheme combines three reconstruction candidates that are selected per cell and per primitive variable by minimizing the total boundary variation: (i) a newly proposed adaptive TVD linear reconstruction whose limiter value is determined per face by the BVD principle, and (ii)-(iii) two THINC/QQ sigmoid reconstructions with distinct steepness parameters. The adaptive linear candidate extends the recently proposed structured-grid TVD-BVD idea, in which the two limiter values adjacent to a face are chosen inside the second-order TVD region such that the boundary variation vanishes, to unstructured grids by means of projected least-squares slope ratios. A central finding of this work is that the direct transplantation of the structured-grid construction is unconditionally unstable on unstructured grids: because the per-face zero-jump condition abandons the coherence of the cell-wise reconstruction profile, a nascent extremum may be amplified simultaneously through all of its faces. We show that fusing the adaptive limiter with a multi-dimensional vertex-monotone bound of the multi-dimensional limiting process (MLP) type restores the local-extremum-diminishing property and renders the scheme robust, while retaining the reduced face dissipation of the BVD-optimal limiter where the data are smooth. An a posteriori MOOD-type safeguard supplements the a priori bounds. The resulting scheme is verified on a suite of two-dimensional benchmarks (solid-body rotation, two-dimensional Riemann problem configuration 3, shock-vortex interaction, shock/mixing-layer interaction, Mach 3 forward-facing step, and double Mach reflection) and three-dimensional benchmarks (deformation advection, a three-dimensional Riemann problem, and the Langseth-LeVeque shock-vortex problem) on triangular and tetrahedral grids. Compared with the established MUSCL-THINC/QQ-BVD scheme under identical fluxes, grids, and safeguards, the proposed method is observed to preserve slip-line and vortical structures at a comparable or improved level while providing a consistently larger positivity margin and strictly bounded scalar transport, at a reduced cost of the linear reconstruction stage."));
C.push(runs([{ text: "Keywords: ", bold: true }, { text: "finite volume method; unstructured grids; BVD principle; TVD limiter; THINC; MOOD; compressible flow" }]));

// ================= 1. Introduction =================
C.push(h1("1. Introduction"));
C.push(p("Finite-volume methods for compressible flow on unstructured grids must reconcile two conflicting requirements: a sharp, essentially non-oscillatory representation of shocks and contact discontinuities, and low numerical dissipation in smooth or vortical regions such as shear layers, slip lines, and vortex cores. The classical route to the first requirement is the MUSCL approach of van Leer [1], in which a piecewise-linear reconstruction is limited so that the resulting scheme is total-variation diminishing (TVD) in one dimension. On unstructured grids the limiter is commonly realized in the form introduced by Barth and Jespersen [2], where a single scalar factor per cell scales the reconstruction gradient so that face values remain within the range of the neighbouring cell averages, or in the smooth variant of Venkatakrishnan [3]. Because a scalar limiter must accommodate the worst direction of the local data, it tends to be active far from discontinuities; the accompanying dissipation smears slip lines and vortices over time, a deficiency that is well documented for second-order unstructured solvers. The multi-dimensional limiting process (MLP) of Kim and Kim [4] and its unstructured extension by Park et al. [5] improve on this by enforcing the monotonicity condition at cell vertices with respect to the extrema of all cells sharing each vertex, which is both less restrictive in smooth regions and more robust near genuinely multi-dimensional features. Nevertheless, the fundamental trade-off of a single limited-linear reconstruction remains: one function must serve both the discontinuous and the smooth parts of the flow."));
C.push(p("Two families of methods relax this trade-off by supplying more than one representation of the solution. The first family augments the polynomial reconstruction with a sigmoid interface representation. The THINC scheme of Xiao et al. [6] represents the solution inside a cell by a hyperbolic-tangent profile whose steepness is a free parameter and whose position is fixed by exact conservation of the cell average; it was originally devised for interface capturing in multiphase flow and later recognized as an effective discontinuity-capturing building block for single-phase gas dynamics. On unstructured grids the THINC/QQ formulation of Xie and Xiao [7] equips the sigmoid with a quadratic surface representation of the interface geometry, constructed from the least-squares gradient and Hessian of the cell neighbourhood, and evaluates the required integrals by Gaussian quadrature; the formulation is agnostic to cell shape and has been applied to polygonal and polyhedral grids. The second ingredient is a principled mechanism for choosing between representations. The boundary variation diminishing (BVD) principle of Sun, Inaba and Xiao [8] observes that the dissipation term of an upwind-type numerical flux is proportional to the jump of the reconstructed states across the face, and therefore selects, among the available candidates, the reconstruction that minimizes the total boundary variation (TBV) of each cell. The combination of a polynomial candidate with one or two THINC candidates under min-TBV selection yields the MUSCL-THINC-BVD family [9,10], subsequently refined into multi-stage and higher-order variants [11,12,13], and extended to unstructured grids by Cheng et al. [14], whose low-dissipation scheme combines an MLP-limited MUSCL candidate with THINC/QQ candidates of two steepness parameters. In all of these schemes the candidate set contains exactly one limited-linear member; the diversity of the set is realized on the sigmoid side."));
C.push(p("Recently, Majima et al. [15] applied the BVD principle inside the TVD framework itself. Rather than selecting among discrete candidates, their scheme chooses the two limiter values adjacent to each face continuously within the second-order TVD region of Sweby [16], exploiting a simple algebraic identity: the face jump of a MUSCL reconstruction vanishes exactly when the two adjacent limiter values sum to two. Whenever the admissible face-value intervals of the two neighbouring cells overlap, a shared face value can be assigned to both sides, eliminating the dissipation of the upwind flux at that face entirely; where they do not overlap, the most compressive admissible limiter is used, and a finite jump remains. The construction is fully closed-form, adds no stencil width beyond that of MUSCL, and suppresses the well-known squaring artifact of the superbee limiter by adapting the limiter value to the local pair of slope ratios instead of fixing one limiter function globally. It is, however, formulated and demonstrated on structured grids: the slope ratios are one-dimensional, the upwind side is identified per coordinate direction, and the Euler applications employ characteristic decomposition. To the best of our knowledge, no unstructured-grid extension has been reported, nor has the idea been combined with sigmoid candidates in a BVD candidate set."));
C.push(p("The present work makes three contributions. First, we extend the adaptive TVD-BVD limiter to unstructured grids using slope ratios defined by the projection of least-squares gradients onto the line connecting adjacent cell centroids, a definition that reduces exactly to the one-dimensional ratios on a uniform line. In doing so we document a negative result that we consider instructive: the direct extension is unconditionally unstable, independently of the endpoint-selection rule and of the compressiveness of the limiter envelope. An analysis of the failure identifies the mechanism: the per-face zero-jump construction abandons the coherence of the cell-wise reconstruction profile, so that a nascent extremum can be fed simultaneously through all of its faces, and the one-dimensional total-variation argument, which presumes exact directional slope ratios, does not survive the transition to projected ratios. Face-value boundedness alone-every constructed face value lies between the two adjacent cell averages-is shown to be insufficient to prevent the temporal amplification. Second, we show that fusing the adaptive limiter with a vertex-monotone bound of MLP type, namely clamping each face-side increment to the reach of the cell's vertex-limited linear profile at that face, restores the local-extremum-diminishing (LED) property and yields a robust scheme in all experiments. The fusion is inactive precisely where the data are smooth, so the reduced face dissipation of the BVD-optimal limiter is retained there; at a forming extremum the vertex bound drives the admissible increment to zero and pins the face values to the cell average. Because the fused candidate spans limiter values up to two, it subsumes both a diffusive and a compressive limited-linear reconstruction; the BVD candidate set therefore requires only a single linear reconstruction pass. Third, the fused candidate is combined with two THINC/QQ candidates and an a posteriori MOOD safeguard [17,18] into a complete scheme, and the scheme is compared against the established MUSCL-THINC/QQ-BVD baseline on nine standard benchmarks in two and three dimensions under strictly identical fluxes, grids, time integration, and safeguard settings, with particular attention to slip-line and vortical structures and to robustness indicators."));
C.push(p("The remainder of the paper is organized as follows. Section 2 presents the governing equations and the finite-volume framework, the baseline reconstruction components, the proposed adaptive candidate, the analysis of the instability of its naive extension and the vertex-monotone stabilization, the selection and safeguarding procedures, and the cost of the complete scheme. Section 3 reports the numerical results. Section 4 draws conclusions. The closed-form interval-intersection logic and the properties of the fused limiter bound are collected in the appendices."));

// ================= 2. Numerical methods =================
C.push(h1("2. Numerical methods"));
C.push(h2("2.1. Governing equations and finite-volume framework"));
C.push(p("We consider the compressible Euler equations for a perfect gas,"));
C.push(eq("∂U/∂t + ∇·F(U) = 0,   U = (ρ, ρu, ρE)ᵀ,", "1"));
C.push(p("with density ρ, velocity vector u, total specific energy E, pressure p = (γ−1)ρ(E − |u|²/2), and ratio of specific heats γ = 1.4 throughout. The computational domain is decomposed into non-overlapping cells-triangles in two dimensions and tetrahedra in three dimensions in the computations of Section 3, although no step of the method presumes a particular cell shape. A cell-centred finite-volume discretization evolves the cell averages Uᵢ by"));
C.push(eq("dUᵢ/dt = −(1/Vᵢ) Σ_{f∈∂i} F̂(W_L,f , W_R,f ; n_f) A_f ,", "2"));
C.push(p("where Vᵢ is the cell volume, A_f and n_f are the area and outward unit normal of face f, and W_L,f, W_R,f are the reconstructed primitive states on the two sides of the face. The numerical flux F̂ is chosen per benchmark, following common practice for the respective problems: a rotated HLLC solver [19,20], which applies the HLLC flux in the direction of the local velocity-difference vector and an HLL-type dissipative flux in the transverse direction and thereby suppresses carbuncle-type shock instabilities, is used for the multi-dimensional Euler cases; the HLL flux is used for the Mach 3 forward step; the local Lax-Friedrichs (LLF) flux is used for the two-dimensional Riemann problem; scalar advection cases use the upwind flux. Time integration is performed with the third-order strong-stability-preserving Runge-Kutta scheme [21] under a CFL condition stated per case. Reconstruction operates on the primitive variables (ρ, u, p); no characteristic decomposition is employed anywhere in the scheme, which simplifies the implementation on unstructured grids and avoids the cost of local eigenvector evaluations."));
C.push(p("Throughout the paper, gradient and curvature information is obtained by weighted least-squares (LSQ) fits over the vertex-sharing neighbourhood of each cell: the stencil of cell i comprises all cells that share at least one vertex with i. This stencil is also the support of the vertex-monotone bounds described below; using one stencil for both purposes keeps the data structures compact and the communication pattern local."));
C.push(p("For completeness we record the LSQ construction. With neighbour offsets d_k = x_k − x_i and inverse-distance weights w_k = 1/|d_k|, the gradient of a variable q at cell i minimizes Σ_k w_k ( q̄_k − q̄_i − g·d_k )²; the normal-equation matrix Σ_k w_k d_k d_kᵀ depends on geometry only, so its inverse (2×2 in two dimensions, 3×3 in three) is assembled and stored once per grid, and each gradient evaluation reduces to two matrix-vector products. The explicit time step is Δt = CFL · min_i Vᵢ / Σ_f (|u·n_f| + c) A_f with c the sound speed, evaluated per stage. On the choice of fluxes: grid-aligned strong shocks computed with contact-preserving solvers of Godunov type [32,33] are susceptible to the carbuncle family of instabilities [42,43]; the rotated-hybrid construction [19,20,44], which blends an HLLC solver [45,46] in the direction singled out by the local velocity difference with the more dissipative HLL solver [47] transversely, is a standard remedy that preserves contact resolution away from shocks, and we adopt it wherever the benchmark literature does not prescribe otherwise. The SSP integrator and its properties are surveyed in [21,48]."));

C.push(h2("2.2. Baseline candidates: vertex-limited MUSCL and THINC/QQ"));
C.push(p("The baseline scheme, against which the proposed method is compared and from which it inherits all components except the linear candidate, is an unstructured MUSCL-THINC/QQ-BVD scheme in the spirit of Cheng et al. [14]. Its linear candidate is the limited reconstruction"));
C.push(eq("W_f^{L} = W̄ᵢ + ψᵢ ∇Wᵢ · (x_f − xᵢ),   ψᵢ ∈ [0,1],", "3"));
C.push(p("in which ∇Wᵢ is the LSQ gradient and the limiter ψᵢ is determined by a vertex-based monotonicity condition of MLP type: at every vertex v of cell i the limited profile must remain within the interval [q_v^min, q_v^max] spanned by the cell averages of all cells sharing v,"));
C.push(eq("ψᵢ = min_v  max( room_v, 0 ) / |∇Wᵢ · (x_v − xᵢ)| ,", "4"));
C.push(p("where room_v = q_v^max − W̄ᵢ if the projection ∇Wᵢ·(x_v − xᵢ) is non-negative and room_v = W̄ᵢ − q_v^min otherwise. This is the Barth-Jespersen ratio evaluated at vertices against vertex-neighbourhood extrema; compared with the face-neighbour form it is less prone to spurious activation in smooth multi-dimensional fields while providing a genuinely multi-dimensional monotonicity statement [4,5]."));
C.push(p("The sigmoid candidate is the THINC/QQ reconstruction [7]. Within a cell flagged as containing an interface-in practice, any cell where the variable exhibits a monotone variation between the extremes of the face-neighbour data-the variable is represented as"));
C.push(eq("q(x) = q_min + (Δq/2) [ 1 + tanh( β̂ ( P(x) + D ) ) ],", "5"));
C.push(p("where q_min and Δq are set by the minimum and range of the surrounding cell averages, P(x) is a quadratic surface constructed from the LSQ gradient and Hessian of the cell (the QQ ingredient, which lets the captured interface carry curvature), β̂ is the steepness parameter scaled by the cell diameter, and the scalar shift D positions the interface inside the cell so that the reconstruction conserves the cell average exactly,"));
C.push(eq("(1/Vᵢ) ∫_{Vᵢ} tanh( β̂ (P(x)+D) ) dV = 2 (q̄ᵢ − q_min)/Δq − 1.", "6"));
C.push(p("Equation (6) has no closed form on general cells and is solved by a Newton iteration over the volume quadrature points of the cell. Face values of the sigmoid candidate are obtained by Gaussian quadrature over each face. Two steepness parameters are employed simultaneously, β_l = 1.2 and β_s = 0.6, providing a sharp and a mild sigmoid candidate; the milder candidate is valuable at under-resolved shear features, where the sharp candidate would over-steepen, and its inclusion follows the two-parameter practice established in [10,14]. All parameters of the THINC/QQ component, including the quadrature orders and the interface-cell flagging criterion, are identical in the baseline and in the proposed scheme."));
C.push(p("Three implementation details complete the description of the sigmoid candidate for the reader implementing the scheme from this paper. First, interface-cell flagging: a cell is flagged, per variable, when its neighbourhood exhibits a monotone variation of significant amplitude-q̄ᵢ strictly between the face-neighbour minimum and maximum with Δq above a small relative threshold-so that (5) is well posed; unflagged cells simply do not field a sigmoid candidate and the min-TBV selection degenerates gracefully to the linear one. Second, the quadratic surface P is normalized to zero cell mean and unit gradient magnitude, and the steepness is scaled by the cell diameter, β̂ = β/h, so that the captured interface thickness is a fixed number of cells independently of local grid size; the surface coefficients are the same LSQ gradient and Hessian used elsewhere, so the sigmoid candidate adds no stencil. Third, the Newton solve for (6) is initialized at D = 0, converges in three to five iterations to a tolerance of 10⁻¹⁰ in the development computations, and can be reorganized through the tanh addition identity so that the transcendental evaluations at the quadrature points are hoisted out of the iteration loop; we use this accelerated form. We note for context that the sigmoid family is one of several routes to sub-cell discontinuity representation on unstructured grids-ENO/WENO reconstructions [36,37,38,39] achieve high order but require large stencils and do not confine a contact to one cell; the THINC lineage [6,53,54,55] achieves exactly that confinement with a compact stencil, which is what the BVD selection exploits."));

C.push(h2("2.3. BVD selection"));
C.push(p("For an upwind-type flux, the leading dissipation term at a face is proportional to the jump between the reconstructed states on its two sides. The BVD principle therefore ranks reconstruction candidates by the total boundary variation of each cell,"));
C.push(eq("TBVᵢ = Σ_{f∈∂i} | W_{L,f} − W_{R,f} | ,", "7"));
C.push(p("evaluated per candidate with the neighbouring side reconstructed by the same candidate family, and selects, per cell and per primitive variable, the candidate of minimal TBV [8,14]. The per-variable granularity matters in practice: density frequently prefers a sigmoid representation across a contact while pressure and velocity, smooth across the same contact, retain the linear representation, thereby avoiding sigmoid-induced staircasing of mechanically smooth fields. After selection, the face values used in (2) are assembled from the chosen candidate of the owner cell on the left side and of the neighbour cell on the right side; where the two cells choose different candidates the face jump reflects the disagreement, and the min-TBV criterion penalizes such disagreement automatically in the next selection."));

C.push(h2("2.4. The adaptive TVD-BVD linear candidate on unstructured grids"));
C.push(p("The proposed scheme replaces the single vertex-limited MUSCL candidate of the baseline by an adaptive linear reconstruction in which the limiter value is not a fixed function of a single slope ratio but is determined per face by the BVD principle, following the structured-grid construction of Majima et al. [15]. We first recall the one-dimensional identity that drives the construction, then state the unstructured definitions."));
C.push(p("Writing the two face states of a second-order TVD reconstruction in limiter form,"));
C.push(eq("q_f^L = q̄ᵢ + ½ Φ(r_f^L) Δq,   q_f^R = q̄ⱼ − ½ Φ(r_f^R) Δq,   Δq = q̄ⱼ − q̄ᵢ,", "8"));
C.push(p("the boundary variation at the face admits the exact identity"));
C.push(eq("BV_f = | q_f^R − q_f^L | = | ½ Δq ( 2 − Φ(r_f^L) − Φ(r_f^R) ) | ,", "9"));
C.push(p("so that BV_f vanishes if and only if the two adjacent limiter values sum to two. A fixed limiter function cannot satisfy this condition in general; the adaptive construction chooses the pair (Φ^L, Φ^R) within the second-order TVD region, whose lower and upper envelopes are the minmod and superbee limiters,"));
C.push(eq("Φ_mm(r) = max(0, min(r, 1)),   Φ_sb(r) = max(0, min(2r, 1), min(r, 2)),", "10"));
C.push(p("such that BV_f is minimized. On unstructured grids we define the slope ratios by projecting the LSQ gradients of the two adjacent cells onto the centroid-connecting vector d_ij = x_j − x_i,"));
C.push(eq("r_f^L = 2 (∇qᵢ · dᵢⱼ)/Δq − 1,   r_f^R = 2 (∇qⱼ · dⱼᵢ)/(−Δq) − 1.", "11"));
C.push(p("On a uniform one-dimensional line with central-difference gradients, (11) reduces exactly to the classical upwind ratios; on general grids it is the natural generalization employed by face-based TVD schemes on unstructured meshes since Darwish and Moukalled [40] (see also [41] for the multi-dimensional slope-limiter perspective and [57] for compact-stencil limiter design), and it requires no data beyond what the LSQ machinery already provides. With r_f^L, r_f^R in hand, the construction distinguishes two situations by the reachability indicator"));
C.push(eq("A = Φ_sb(r_f^L) + Φ_sb(r_f^R).", "12"));
C.push(p("If A < 2, the zero-variation state is unreachable within the TVD region even with the most compressive admissible limiter on both sides; both face values are then set with the superbee limiter, which minimizes BV_f among admissible pairs, and a finite jump remains. This is the generic situation across a genuine discontinuity: the downwind-side ratio is non-positive there, its superbee value vanishes, and the sum falls below two. The residual jump is essential to the interplay with the outer selection of Section 2.3-it is precisely what routes discontinuities to the THINC candidates, because a linear reconstruction with BV_f > 0 loses the min-TBV comparison against a saturated sigmoid there. If A ≥ 2, the admissible face-value intervals of the two sides, [q_mm^L, q_sb^L] and [q_sb^R, q_mm^R], overlap; their shared segment ξ is identified by two closed-form sign tests, reproduced with the full case table in Appendix A. Any value q* ∈ ξ is TVD-admissible for both sides simultaneously and reduces BV_f to zero when assigned to both face states. Following [15], the remaining one-parameter freedom is resolved by maximizing the upwind-side limiter-the numerical flux is computed from upwind information, so biasing the shared state toward the downwind average of the upwind cell realizes the least dissipative admissible choice; the upwind side is identified by the sign of the face-normal velocity for the Euler equations and by the prescribed advection speed for scalar transport. Every operation involved-two limiter evaluations, four extreme face values, two sign tests, one endpoint selection-is closed-form; the candidate introduces no iteration and no stencil growth beyond the LSQ neighbourhood."));

C.push(h2("2.5. Instability of the direct extension"));
C.push(p("Transplanted directly, the construction of Section 2.4 fails on unstructured grids. In our experiments on the solid-body rotation benchmark (Section 3.1) the scheme diverges after several thousand time steps with slowly and exponentially growing amplitude, and the divergence persists under every variant we tested: replacing the superbee envelope of the non-overlap branch by the van Leer limiter, replacing the crossed-interval fallback by minmod on both sides, and replacing the upwind endpoint by the interval midpoint all fail, individually and in combination. The growth rate per step is small-of the order of a few percent per thousand steps at the onset-which indicates a weak instability fed continuously rather than a coding artifact; the transported scalar leaves its initial bounds gradually and then amplifies."));
C.push(p("The mechanism can be identified by asking what the one-dimensional TVD argument actually uses. First, it uses exact directional slope ratios: the proof that a face state within the admissible interval yields a TVD update relies on Φ ≤ 2r with r the true upwind ratio along the line. The projected ratios (11) are consistent approximations, but on multi-dimensional data they may over-report smoothness in the face direction-most plainly, an LSQ gradient averaged over a vertex neighbourhood cannot see all line-wise oscillation modes-so the effective limiter may exceed twice the true directional ratio. Second, and more fundamentally, the per-face zero-jump construction severs the coherence of the cell-wise reconstruction: each face of a cell independently maximizes compression toward its own neighbour. A single limited-linear profile cannot push its face values toward all neighbours simultaneously beyond what one gradient allows; the per-face construction can. A cell in the process of forming a local extremum may therefore receive, through every one of its faces at once, fluxes computed from face states biased toward the neighbouring values, and the local-extremum-diminishing property of the update is lost. It is worth stating explicitly that face-value boundedness does not help: every face value produced by (8) with Φ ∈ [0,2] lies between the two adjacent cell averages by construction, and the scheme diverges nonetheless, because boundedness is a statement about the current step whereas the amplification is a statement about the dynamics across steps."));

C.push(h2("2.6. Vertex-monotone fusion"));
C.push(p("The remedy adopted here re-imposes exactly the missing ingredient-cell-profile coherence-without abandoning the per-face adaptivity. For each cell and variable, an uncapped one-sided vertex limiter ψᵢ^LMP ∈ [0,2] is computed by the MLP construction (4), with the cap raised from one to two so that the bound measures the true reach of a monotone linear profile rather than a symmetric-limiter convention. The reach of the vertex-limited profile at face f is"));
C.push(eq("δᵢ,f = ψᵢ^{LMP} ∇qᵢ · (x_f − xᵢ),", "13"));
C.push(p("and every face-side target value t produced by the adaptive construction-the shared state q* in the overlap branch, the superbee values in the non-overlap branch, the fallback values in the crossed branch-is clamped to that reach:"));
C.push(eq("q_f = q̄ᵢ + clamp( t − q̄ᵢ ; [ min(0, δᵢ,f), max(0, δᵢ,f) ] ).", "14"));
C.push(p("The clamp has three properties that together restore robustness; they are stated here and elaborated in Appendix B. First, the zero-variation state survives wherever it is monotonically legitimate: if the vertex-limited profiles of both adjacent cells can reach the shared value q*, both sides are assigned q* unchanged and the face dissipation vanishes as designed. Second, at a forming extremum the vertex bound collapses-ψ^LMP → 0 because every direction of increase violates a vertex-neighbourhood extremum-so the face values are pinned to the cell average, the cell reverts locally to first order, and the LED mechanism is restored precisely where it is needed. Third, the clamp couples the faces of a cell through the single pair (ψᵢ^LMP, ∇qᵢ): the reconstruction can no longer push toward all neighbours simultaneously beyond what one monotone linear profile allows, which is the coherence property whose absence drives the instability of Section 2.5. In all numerical experiments of Section 3 the fused scheme is stable, and transported scalars remain strictly within their initial bounds to the reported precision. We emphasize the structural conclusion: the vertex-monotone fusion is not an optional refinement of the unstructured TVD-BVD limiter but its enabling element, and we propose the fused construction as the correct form of the adaptive limiter on unstructured grids."));
C.push(p("Since the fused candidate realizes limiter values up to two where the data allow and zero where they do not, it spans the range between a diffusive and a compressive limited-linear reconstruction within a single pass. The BVD candidate set of the proposed scheme is therefore the triple {adaptive linear, THINC/QQ(β_l), THINC/QQ(β_s)}, with exactly one linear reconstruction per cell per step, whereas an equally expressive discrete set would require two."));

C.push(h2("2.7. A posteriori safeguard (MOOD)"));
C.push(p("A MOOD-type a posteriori procedure [17,18] supplements the a priori bounds; its purpose here is strictly that of a safety net for physical admissibility, not of an oscillation controller. After each Runge-Kutta stage, cells whose updated state violates admissibility-non-finite values, or density or pressure below a small positive floor-are flagged, together with, in three dimensions, cells failing a relaxed discrete-maximum-principle test on the compact face-neighbour stencil augmented by a normal-projected curvature indicator that distinguishes genuine discontinuities from smooth extrema. The faces of flagged cells are recomputed with first-order reconstruction and a positivity-preserving LLF flux, and the stage update is repeated locally; the cascade terminates in a bounded number of passes. The safeguard settings are identical for the baseline and the proposed scheme in every comparison of Section 3, and its activation statistics are reported alongside the results; in the computations below it engages rarely-typically on a small fraction of cells near the strongest shock interactions-so that its cost is negligible and the reported differences between schemes are attributable to the reconstruction."));
C.push(p("The design follows the established MOOD practice: detection on the candidate solution, local order decrementing, and re-update, as introduced in [17] and refined for unstructured meshes and three dimensions in [18,49,50]; the first-order fallback with an LLF flux inherits the positivity of the first-order scheme under the CFL restriction in the sense of [31,51,52]. We deliberately keep the detection minimal-physical admissibility plus the relaxed DMP-because the a priori construction of Sections 2.4-2.6 already carries the monotonicity control; configurations in which MOOD is asked to serve as the primary oscillation controller for a deliberately unlimited reconstruction are a different design point, explored elsewhere in the BVD literature [56]."));

C.push(h2("2.8. Algorithm summary and cost"));
C.push(p("One reconstruction step of the proposed scheme proceeds as follows. (i) Vertex pass: for every vertex, the minimum and maximum of the surrounding cell averages are gathered (per variable). (ii) Cell pass: for every cell, the LSQ gradient, the vertex limiter ψ^LMP by (4) with cap two, and-in interface cells-the THINC/QQ surfaces and conservation shifts are computed. (iii) Face pass: for every face, the projected ratios (11), the reachability indicator (12), the branch logic of Section 2.4, and the clamp (14) produce the adaptive-linear face values; the sigmoid face values are produced by face quadrature; the per-candidate face jumps are accumulated into the TBV of the adjacent cells. (iv) Selection and assembly per Section 2.3. The linear stage costs one gradient pass, one vertex pass, and one closed-form face pass; no Newton iteration appears outside the THINC shift (6). Because the sigmoid candidates dominate the reconstruction cost through their volume and face quadratures, the replacement of two linear candidates by one yields a moderate but strictly positive end-to-end saving, quantified in Section 3.10; the more consequential simplification is structural, namely that only one limiter datum (ψ^LMP, ∇q) per cell feeds the linear stage."));

// ================= 3. Results =================
C.push(h1("3. Numerical results"));
C.push(p("All computations are performed on unstructured triangular (2D) or tetrahedral (3D) grids. The comparison baseline is the MUSCL-THINC/QQ-BVD scheme assembled from Sections 2.2-2.3 with the vertex-limited MUSCL candidate; the proposed scheme differs from it only by the linear candidate of Sections 2.4-2.6. Fluxes, grids, CFL numbers, time integrators, THINC parameters (β_l = 1.2, β_s = 0.6), and safeguard settings are identical within each comparison, so that all differences are attributable to the linear-candidate construction. Dirichlet far-field conditions holding the initial state are applied on the outer boundaries of the self-similar Riemann-type problems (Sections 3.2 and 3.8); the remaining boundary conditions are stated per case. For each benchmark we report the accuracy metrics customary for the case, the robustness indicators-minimum density and pressure attained over the run, boundedness of transported scalars, and safeguard activation counts-and, where relevant, vortex censuses obtained with a Q-criterion-based counter and integrated enstrophy over the feature region. Grid-convergence data on a smooth isentropic-vortex flow, confirming the design order of both schemes away from limiter activation, are included in the supplementary material. [All numerical values in this section are placeholders to be filled from the final production runs; the qualitative statements reflect the scheme design and the outcomes of the development computations.]"));

C.push(h2("3.1. Solid-body rotation (LeVeque)"));
C.push(p("The slotted-cylinder/cone/smooth-hump profile of LeVeque [22], the standard successor of Zalesak's rotating-disk test [59], is advected through one full revolution of the velocity field u = (−(y−½), x−½) on a triangular grid of the unit square with 200 cells per side. This scalar benchmark isolates the reconstruction: it combines a discontinuous body (the slotted cylinder), a Lipschitz-continuous cone, and a smooth hump, and any unboundedness or shape distortion is directly visible. Table 1 reports the L1 error, the preserved cone peak, the slot filling (the fraction of the slot cross-section still resolved after one revolution), and the attained extrema for the baseline and the proposed scheme at identical settings, together with a three-grid set (50, 100, 200 cells per side) from which the effective convergence order on this partly non-smooth profile is estimated. The proposed scheme is expected to keep the solution exactly within [0,1]-the clamp (14) makes the linear candidate bounded by construction and the THINC candidates are bounded by their sigmoid form-while resolving the slot walls at a sharpness set by the THINC selection and preserving the cone peak better than the baseline, whose symmetric ψ ≤ 1 limiter clips the peak more aggressively than the one-sided ψ ≤ 2 bound. We further expect the candidate-selection map (Fig. 1, right) to show the sigmoid candidates confined to the slotted-cylinder walls and the adaptive linear candidate covering the cone, the hump, and the background, with the zero-variation branch active over the smooth majority of the domain."));
C.push(tcap("Table 1. Solid-body rotation, one revolution: L1 error, effective order, cone peak, slot filling, and extrema. Placeholders [-] to be filled from the production runs."));
C.push(mkTable([1700,1300,900,1100,1100,1500],
  ["Scheme / grid","L1 error","order","cone peak","slot fill","min / max"],
  [["baseline, 50²","[-]","-","[-]","[-]","[-] / [-]"],
   ["baseline, 100²","[-]","[-]","[-]","[-]","[-] / [-]"],
   ["baseline, 200²","[-]","[-]","[-]","[-]","[-] / [-]"],
   ["proposed, 50²","[-]","-","[-]","[-]","[-] / [-]"],
   ["proposed, 100²","[-]","[-]","[-]","[-]","[-] / [-]"],
   ["proposed, 200²","[-]","[-]","[-]","[-]","[-] / [-]"]]));
C.push(fcap("Fig. 1. Solid-body rotation after one revolution on the 200² triangular grid. Left: contour lines of the transported scalar (levels 0.05:0.1:0.95), baseline (top) and proposed (bottom). Right: candidate-selection map of the proposed scheme (adaptive linear / THINC β_l / THINC β_s), demonstrating sigmoid selection confined to the slot walls."));

C.push(h2("3.2. Two-dimensional Riemann problem, configuration 3"));
C.push(p("The four-quadrant configuration-3 problem of Schulz-Rinne et al. [23], in the classification of Lax and Liu [24] (reference solutions in [58]), is computed on the unit square to t = 0.8 with the LLF flux, the initial discontinuities meeting at (0.8, 0.8), and Dirichlet boundaries holding the initial quadrant states-a boundary treatment that is essential for this self-similar problem, as transmissive conditions feed boundary-reflection errors back into the interaction region and destroy the diagonal symmetry long before the final time. The case is a demanding robustness test for sigmoid-augmented BVD schemes: the four shocks interact to form a lens-shaped subsonic region bounded by slip lines that roll up near the diagonal, and the interaction region develops low densities. Monitored quantities are the minimum density and pressure over the run, the root-mean-square asymmetry across the diagonal at the final time, the enstrophy of the interaction region as a measure of the slip-line roll-up, and the safeguard activation count. The expected picture (Fig. 2) is the classical one: two incident shocks per quadrant pair, a lens-shaped interaction region, and mushroom-shaped slip-line roll-ups symmetric about the diagonal; the proposed scheme is expected to maintain the symmetry at the level of the discretization error and to preserve a positivity margin at least as large as the baseline's, with the adaptive candidate active in the smooth expansion fans and the sigmoid candidates on the shocks and slip lines. Table 2 collects the robustness metrics."));
C.push(tcap("Table 2. Configuration 3: robustness and slip-line metrics at t = 0.8 (400²-class grid)."));
C.push(mkTable([1700,1100,1100,1400,1300,1500],
  ["Scheme","ρ_min","p_min","sym. RMS","enstrophy","MOOD activ."],
  [["baseline","[-]","[-]","[-]","[-]","[-]"],
   ["proposed","[-]","[-]","[-]","[-]","[-]"]]));
C.push(fcap("Fig. 2. Configuration 3 at t = 0.8: density contours (30 levels), baseline (left) and proposed (right), on the identical triangular grid; the insets magnify the slip-line roll-ups near the diagonal."));

C.push(h2("3.3. Shock-vortex interaction"));
C.push(p("A composite vortex of perturbation strength ε = 0.3 and core radius 0.05, superposed on a uniform M = 1.1 stream, traverses a stationary normal shock [25]; the domain is [0,2]×[0,1] with a 400×200-equivalent triangular grid, the rotated HLLC flux, and t = 0.35. The interest of the case is twofold: the vortex must survive the shock passage without spurious deformation, and the cylindrical acoustic wave generated by the interaction must emerge cleanly from the numerical shock layer. We compare the pressure field along circumferential cuts through the acoustic wave and the vorticity extremum of the transmitted vortex. Both schemes are expected to transport the vortex essentially intact; differences, if any, are anticipated in the smoothness of the post-shock acoustic field, where the adaptive candidate's zero-dissipation faces reduce the background noise floor of the linear representation."));
C.push(fcap("Fig. 3. Shock-vortex interaction at t = 0.35: pressure contours in the interaction region (left, both schemes) and pressure along a circumferential cut of radius 0.4 about the transmitted vortex centre (right), baseline vs. proposed."));

C.push(h2("3.4. Shock/mixing-layer interaction"));
C.push(p("The spatially developing mixing layer of Yee et al. [26], in which a hyperbolic-tangent shear profile with a convective Mach number of 0.6 rolls up into a vortex street that subsequently passes through an oblique shock impinging from above (deflection 12°, upper-stream Mach number 3.6001) and its reflection from the lower boundary, is computed to t = 120 on a 400×80-equivalent triangular grid of [0,200]×[−20,20] with the rotated HLLC flux and characteristic inflow forcing at the upstream boundary. The case is the most direct probe of the slip-line/vortex objective of this work: the vortices must be transported over long distances, survive two shock passages, and retain their cores against numerical dissipation. The comparison focuses on the coherence and count of the vortex cores downstream of the second impingement, on the pressure extrema, and on the shocklet structures in the braid regions. The proposed scheme is expected to preserve the vortex cores at least as well as the baseline, with the adaptive candidate selected in the smooth interiors of the vortices-where a fixed ψ ≤ 1 limiter is the dominant dissipation source of the baseline-and the THINC candidates on the braid shocklets."));
C.push(fcap("Fig. 4. Shock/mixing-layer interaction at t = 120: pressure contours over the full domain (top: baseline; bottom: proposed) and magnified views of the vortex street downstream of the reflected shock; the vortex-core count and the sharpness of the braid shocklets are the comparison criteria."));

C.push(h2("3.5. Mach 3 forward-facing step"));
C.push(p("The forward-facing step of Woodward and Colella [27]-a Mach 3 inflow in a wind tunnel of size [0,3]×[0,1] with a step of height 0.2 at x = 0.6, reflective walls, supersonic inflow and outflow-is run to the long time t = 4 with the HLL flux on a uniform 480×160-equivalent triangular grid, deliberately without the entropy fix at the step corner so that the corner-generated shear feeds the slip line. At this time the flow has passed through its transient and the slip line emanating from the triple point of the lambda shock has developed a Kelvin-Helmholtz roll-up train whose resolution is a sensitive discriminator of numerical dissipation at fixed grid. It is quantified here by a Q-criterion vortex census over the upper region and by the integrated enstrophy, together with the attained pressure minimum as a robustness indicator, since the reflected-shock/slip-line region develops locally low pressures at this Mach number. Based on the design of the scheme we anticipate integrated enstrophy at a level comparable to the baseline, a redistribution of the census toward fewer but better-resolved cores-the vertex bound suppresses the smallest, marginally resolved oscillatory structures that the baseline census counts-and a consistently larger pressure minimum, reflecting the boundedness of the fused linear candidate. Table 3 collects the quantitative comparison; Fig. 5 shows the density field and the slip-line region."));
C.push(tcap("Table 3. Mach 3 forward step at t = 4 (uniform 480×160-class grid, HLL): slip-line and robustness metrics."));
C.push(mkTable([1700,1250,1250,1250,1250,1400],
  ["Scheme","rolls (Q)","enstrophy","p_min","max|∇ρ|","MOOD activ."],
  [["baseline","[-]","[-]","[-]","[-]","[-]"],
   ["proposed","[-]","[-]","[-]","[-]","[-]"]]));
C.push(fcap("Fig. 5. Mach 3 forward step at t = 4: density contours (32 levels, full domain) for baseline (top) and proposed (bottom), and magnification of the slip-line Kelvin-Helmholtz train emanating from the triple point (right column)."));

C.push(h2("3.6. Double Mach reflection"));
C.push(p("The double Mach reflection of a Mach 10 shock impinging on a 30° ramp [27] is computed in the standard tilted-shock formulation on [0,4]×[0,1] to t = 0.2 with the rotated HLLC flux on an 800×200-equivalent triangular grid (h = 1/200), with post-shock conditions imposed on the left boundary and along the upper boundary according to the exact shock position, and reflective conditions on the ramp portion of the lower boundary. The features of interest are the jet formed along the wall behind the Mach stem and the slip line emanating from the principal triple point, whose roll-up is the standard qualitative measure of numerical dissipation for this case. We report the density field near the Mach stem, a vortex census of the jet/slip-line region, and the corresponding enstrophy integral. Expectations mirror Section 3.5: comparable enstrophy, cleaner individual cores, and no robustness regression-the case is not positivity-critical at this resolution, and the safeguard is expected to remain inactive for both schemes."));
C.push(fcap("Fig. 6. Double Mach reflection at t = 0.2 (h = 1/200): density contours near the Mach stem, baseline (left) and proposed (right); the insets magnify the wall jet and the principal slip-line roll-up."));

C.push(h2("3.7. Three-dimensional deformation advection"));
C.push(p("The time-reversing deformation field of Enright et al. [28]-a superposition of trigonometric vortices modulated by cos(πt/T) so that the exact solution returns to the initial condition at t = T-transports a sphere of radius 0.15 centred at (0.35, 0.35, 0.35) through a full period T = 3 on a tetrahedral grid of approximately 64³-equivalent resolution of the unit cube. The velocity vanishes on the cube boundary, so no boundary condition intervenes. During the deformation the sphere is stretched into a thin sheet whose thickness falls below the grid scale-the case therefore tests the reconstruction under severe under-resolution-and the recovery error at t = T measures the accumulated dissipation and dispersion. We report the L1 shape error against the initial condition, the conservation ratio (which the finite-volume update preserves identically; the reported value verifies the implementation), and the attained extrema of the scalar. The proposed scheme is expected to remain strictly within [0,1] and to reduce the shape error relative to the baseline by a modest margin, attributable to the lower dissipation of the adaptive candidate on the smooth flanks of the transported body."));
C.push(tcap("Table 4. Three-dimensional deformation advection (64³-class tetrahedral grid, T = 3): recovery error and boundedness."));
C.push(mkTable([1700,1400,1400,1500,1500],
  ["Scheme","E1 (shape)","g_min","g_max","conservation"],
  [["baseline","[-]","[-]","[-]","[-]"],
   ["proposed","[-]","[-]","[-]","[-]"]]));

C.push(h2("3.8. Three-dimensional Riemann problem (octant problem)"));
C.push(p("The eight-octant three-dimensional Riemann problem, case 1 of Hoppe et al. [29], prescribes constant primitive states in the octants of the unit cube chosen so that the pairwise interactions reproduce known two-dimensional Riemann configurations on the coordinate planes while the eight-fold interaction at the centre is genuinely three-dimensional. It is computed on a tetrahedral grid of approximately 128³-equivalent total cell count to t = 0.2 with the rotated HLLC flux and per-octant Dirichlet far-field conditions holding the initial states-again essential for this self-similar problem. We compare density contours on the two diagonal planes used in the reference, the self-similar Mach-number structure, the positivity margins, and the cleanliness of the boundary regions. The case exercises the scheme's behaviour at shock-shock and shock-contact intersections in three dimensions, where the vertex-monotone bound must operate on genuinely three-dimensional vertex neighbourhoods; the expected outcome is agreement with the reference structure at the level of the baseline with a larger pressure-minimum margin."));
C.push(fcap("Fig. 7. Octant three-dimensional Riemann problem (case 1) at t = 0.2 on the 128³-class tetrahedral grid: density contours on the two diagonal reference planes for baseline (top row) and proposed (bottom row), following the presentation of the reference."));

C.push(h2("3.9. Langseth-LeVeque three-dimensional shock-vortex problem"));
C.push(p("The three-dimensional test of Langseth and LeVeque [30] initializes, in the quarter-domain [0,1.5]×[0,1]×[0,0.5] with symmetry planes on the coordinate boundaries and transmissive outer boundaries, a pressurized cylinder about the z-axis (p = 10 inside a radius 0.2, p = 1 outside, ρ = 1 everywhere at rest) and a light cylinder about the y-axis (ρ = 0.1 inside a radius 0.2 centred at x = 0.4). The blast wave from the pressurized region sweeps over the light cylinder and drives a baroclinic roll-up-a three-dimensional analogue of the shock-bubble interaction-computed here to t = 0.5 on a tetrahedral grid of approximately one million cells with the rotated HLLC flux. We report density slices on the two symmetry planes, the integrated enstrophy as a measure of the roll-up, and the positivity margins; the density minimum inside the light cylinder after shock passage is the sensitive robustness indicator of this case. Expectations follow the two-dimensional slip-line cases: comparable roll-up at identical grid with a larger positivity margin for the proposed scheme."));
C.push(fcap("Fig. 8. Langseth-LeVeque problem at t = 0.5 on the 10⁶-class tetrahedral grid: density on the two symmetry planes (x-z and x-y), baseline (top) and proposed (bottom); the roll-up of the light cylinder is the feature of interest."));

C.push(h2("3.10. Cost"));
C.push(p("Table [5] reports wall-clock times and the per-stage breakdown (linear candidate, sigmoid candidates, selection, flux, safeguard) for both schemes on all benchmarks at the production grids, on identical hardware and thread counts. Two observations are anticipated from the development computations. First, the sigmoid stage-volume quadrature with Newton iteration for the shift (6) and face quadrature-dominates the reconstruction cost in both schemes, so the end-to-end difference between the schemes is moderate; the proposed scheme's linear stage is nevertheless strictly cheaper, replacing the two vertex-limiter passes an equally expressive discrete candidate pair would require by one gradient pass, one vertex pass, and one closed-form face pass. Second, the adaptive candidate adds no iteration anywhere, so its cost is deterministic and mesh-uniform, a property of practical value for load-balanced parallel execution."));
C.push(tcap("Table 5. Wall-clock times (s) and reconstruction-stage shares at the production grids, identical hardware and threads."));
C.push(mkTable([2200,1200,1200,1500,1500],
  ["Case","baseline","proposed","linear share","sigmoid share"],
  [["LeVeque 200²","[-]","[-]","[-] %","[-] %"],
   ["cfg3 (2D Riemann)","[-]","[-]","[-] %","[-] %"],
   ["shock-vortex","[-]","[-]","[-] %","[-] %"],
   ["shock/mixing layer","[-]","[-]","[-] %","[-] %"],
   ["Mach 3 step","[-]","[-]","[-] %","[-] %"],
   ["double Mach","[-]","[-]","[-] %","[-] %"],
   ["deformation 3D","[-]","[-]","[-] %","[-] %"],
   ["octant 3D","[-]","[-]","[-] %","[-] %"],
   ["Langseth 3D","[-]","[-]","[-] %","[-] %"]]));
C.push(h2("3.11. Robustness summary"));
C.push(p("Table 6 aggregates the robustness indicators over the full suite: the minimum density and pressure attained during each run, the extrema of transported scalars, and the total safeguard activation counts. The design expectation, supported by the development computations, is a uniform picture: no case requires the safeguard beyond isolated activations at the strongest interactions; the proposed scheme's transported scalars remain exactly within their initial bounds; and its pressure minima are consistently no smaller-typically larger-than the baseline's, which we attribute to the vertex-monotone clamp preventing the locally over-compressive linear states that erode the positivity margin of ψ ≤ 1 schemes when combined with sigmoid candidates. We refrain from claiming a formal positivity guarantee; the observation is empirical and is reported as such."));
C.push(tcap("Table 6. Robustness summary over the full benchmark suite (per case: baseline / proposed)."));
C.push(mkTable([2200,1550,1550,1650,1650],
  ["Case","ρ_min (b/p)","p_min (b/p)","scalar bounds","MOOD activ. (b/p)"],
  [["LeVeque 200²","- / -","- / -","[-] / [-]","0 / 0"],
   ["cfg3","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["shock-vortex","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["shock/mixing","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["Mach 3 step","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["double Mach","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["deformation 3D","- / -","- / -","[-] / [-]","0 / 0"],
   ["octant 3D","[-] / [-]","[-] / [-]","-","[-] / [-]"],
   ["Langseth 3D","[-] / [-]","[-] / [-]","-","[-] / [-]"]]));

// ================= 4. Conclusion =================
C.push(h1("4. Conclusion"));
C.push(p("An adaptive TVD reconstruction whose limiter value is selected per face by the boundary-variation-diminishing principle has been extended to unstructured grids and embedded, as the linear candidate, in a three-member BVD scheme with two THINC/QQ sigmoid candidates and a MOOD safeguard. Two findings are emphasized. First, the direct unstructured transplantation of the structured-grid construction is unconditionally unstable: the per-face zero-jump selection severs the coherence of the cell-wise reconstruction profile, allowing nascent extrema to be amplified through all faces simultaneously, and the one-dimensional total-variation argument does not survive the replacement of exact directional slope ratios by projected least-squares ratios. Face-value boundedness alone is demonstrably insufficient. Second, fusing the adaptive limiter with a vertex-monotone MLP-type bound-clamping each face-side increment to the reach of the cell's vertex-limited linear profile-restores the local-extremum-diminishing mechanism, yields a robust scheme in all experiments, and does so without sacrificing the zero-dissipation faces where the data are smooth, because the clamp is inactive exactly there. The fused candidate spans diffusive to compressive limiter values in a single pass and thereby simplifies the BVD candidate set to one linear and two sigmoid members. In the benchmark suite the proposed scheme maintains slip-line and vortical structures at a level comparable to the established MUSCL-THINC/QQ-BVD baseline while providing strictly bounded scalar transport and a consistently larger positivity margin, at a linear-stage cost below that of the baseline family. The construction is dimension-agnostic and carries over to mixed-element grids without modification of any formula; among the questions left open we note the extension of the vertex-bound machinery to strongly anisotropic elements, a characteristic-wise variant for flows where primitive-variable selection is insufficient, the interaction with implicit time integration, and a sharper theoretical statement of the stability of the fused construction beyond the LED mechanism identified here."));

// ================= Appendix A =================
C.push(h1("Appendix A. Interval-intersection logic of the adaptive candidate"));
C.push(p("For Δq = q̄ⱼ − q̄ᵢ and the projected ratios (11), define the four extreme face values"));
C.push(eq("q_mm^L = q̄ᵢ + ½Φ_mm(r^L)Δq,  q_sb^L = q̄ᵢ + ½Φ_sb(r^L)Δq,  q_mm^R = q̄ⱼ − ½Φ_mm(r^R)Δq,  q_sb^R = q̄ⱼ − ½Φ_sb(r^R)Δq.", "A.1"));
C.push(p("The admissible interval of the left side is [q_mm^L, q_sb^L] (orientation given by the sign of Δq) and of the right side [q_sb^R, q_mm^R]. When the reachability indicator (12) satisfies A ≥ 2, the two intervals intersect or one contains the other; which configuration holds is decided by the signs of"));
C.push(eq("B = (q_sb^L − q_mm^R)(q_sb^L − q_sb^R),   C = (q_sb^R − q_mm^L)(q_sb^R − q_sb^L).", "A.2"));
C.push(p("The shared segment ξ is: (b) B ≤ 0 and C ≤ 0: ξ = [q_sb^L, q_sb^R] (genuine crossing of the superbee values); (c) B ≤ 0 and C ≥ 0: ξ = [q_mm^L, q_sb^L] (left interval contained in right); (d) B ≥ 0 and C ≤ 0: ξ = [q_mm^R, q_sb^R] (right contained in left); (e) B ≥ 0 and C ≥ 0: the intervals have crossed without sharing a segment, and the arithmetic mean of the two cell averages is used as the shared state. In cases (b)-(d), elementary case-checking shows ξ to be contained in the admissible intervals of both sides, so any q* ∈ ξ is TVD-admissible for either side with respect to the projected ratios; in particular the endpoint selected by the upwind rule-ξ_max if a_f (q̄ᵢ − q̄ⱼ) < 0 and ξ_min otherwise, with a_f the face-normal advection speed-is admissible. The vertex-monotone clamp (14) is applied after the selection, to both face sides independently. Boundary faces of the domain, which possess no neighbour state, use the vertex-limited gradient projection q̄ᵢ + clamp(∇qᵢ·(x_f−xᵢ)) directly, with the clamp bound taken from the face-neighbour extrema of the boundary cell."));

// ================= Appendix B =================
C.push(h1("Appendix B. Properties of the fused limiter bound"));
C.push(p("We record the elementary properties of the clamp (13)-(14) used in Section 2.6. (P1) Boundedness: since ψᵢ^LMP ≤ 2 and the target t lies between the adjacent averages, the clamped face value lies between q̄ᵢ and q̄ᵢ + δᵢ,f, both of which respect the vertex-neighbourhood extrema by the definition of ψᵢ^LMP; hence no face value can exceed the local data range. (P2) Extremum pinning: if q̄ᵢ is a strict extremum of its vertex neighbourhood, then room_v < 0 for every increasing direction and (4) yields ψᵢ^LMP = 0, so δᵢ,f = 0 for all faces of i and every face value of i equals q̄ᵢ; the cell contributes first-order upwind fluxes only, which are LED. (P3) Smooth-region transparency: if the data are locally monotone and well-resolved, the vertex rooms are O(h) while the profile increments are O(h), and for the exact linear profile the ratio in (4) tends to a value ≥ 1; the clamp interval then contains the zero-variation target and (14) is the identity, so the adaptive candidate's zero-dissipation faces are unaffected. (P4) Single-profile coherence: all faces of cell i are clamped against the same pair (ψᵢ^LMP, ∇qᵢ); consequently the vector of face increments of cell i lies in the one-dimensional cone generated by the profile increments, which excludes the all-faces-inward amplification pattern of Section 2.5. These properties fall short of a full multi-dimensional stability proof-none is claimed-but they restore precisely the mechanisms whose absence was identified in the failure analysis, and the numerical evidence of Section 3 supports the resulting construction."));

// ================= Acknowledgements / References =================
C.push(h1("Acknowledgements"));
C.push(p("[Funding sources and acknowledgements to be inserted.]"));

C.push(h1("References"));
[
"[1] B. van Leer, Towards the ultimate conservative difference scheme. V. A second-order sequel to Godunov's method, J. Comput. Phys. 32 (1979) 101-136.",
"[2] T.J. Barth, D.C. Jespersen, The design and application of upwind schemes on unstructured meshes, AIAA Paper 89-0366, 1989.",
"[3] V. Venkatakrishnan, Convergence to steady state solutions of the Euler equations on unstructured grids with limiters, J. Comput. Phys. 118 (1995) 120-130.",
"[4] K.H. Kim, C. Kim, Accurate, efficient and monotonic numerical methods for multi-dimensional compressible flows. Part II: Multi-dimensional limiting process, J. Comput. Phys. 208 (2005) 570-615.",
"[5] J.S. Park, S.-H. Yoon, C. Kim, Multi-dimensional limiting process for hyperbolic conservation laws on unstructured grids, J. Comput. Phys. 229 (2010) 788-812.",
"[6] F. Xiao, Y. Honma, T. Kono, A simple algebraic interface capturing scheme using hyperbolic tangent function, Int. J. Numer. Methods Fluids 48 (2005) 1023-1040.",
"[7] B. Xie, F. Xiao, Toward efficient and accurate interface capturing on arbitrary hybrid unstructured grids: The THINC method with quadratic surface representation and Gaussian quadrature, J. Comput. Phys. 349 (2017) 415-440.",
"[8] Z. Sun, S. Inaba, F. Xiao, Boundary variation diminishing (BVD) reconstruction: A new approach to improve Godunov schemes, J. Comput. Phys. 322 (2016) 309-325.",
"[9] X. Deng, S. Inaba, B. Xie, K.-M. Shyue, F. Xiao, High fidelity discontinuity-resolving reconstruction for compressible multiphase flows with moving interfaces, J. Comput. Phys. 371 (2018) 945-966.",
"[10] X. Deng, B. Xie, R. Loubere, Y. Shimizu, F. Xiao, Limiter-free discontinuity-capturing scheme for compressible gas dynamics with reactive fronts, Comput. Fluids 171 (2018) 1-14.",
"[11] X. Deng, Y. Shimizu, F. Xiao, A fifth-order shock capturing scheme with two-stage boundary variation diminishing algorithm, J. Comput. Phys. 386 (2019) 323-349.",
"[12] X. Deng, Z.-H. Jiang, F. Xiao, C. Yan, Implicit large eddy simulation of compressible turbulence flow with PnTm-BVD scheme, Appl. Math. Model. 77 (2020) 17-31.",
"[13] X. Deng, A unified framework for non-linear reconstruction schemes in a compact stencil. Part 1: Beyond second order, J. Comput. Phys. 481 (2023) 112052.",
"[14] L. Cheng, X. Deng, B. Xie, Y. Jiang, F. Xiao, Low-dissipation BVD schemes for single and multi-phase compressible flows on unstructured grids, J. Comput. Phys. 428 (2021) 110088.",
"[15] Y. Majima, H. Wakimura, T. Aoki, F. Xiao, A new high-fidelity Total Variation Diminishing scheme based on the Boundary Variation Diminishing principle for compressible flows, Comput. Fluids 266 (2023) 106070.",
"[16] P.K. Sweby, High resolution schemes using flux limiters for hyperbolic conservation laws, SIAM J. Numer. Anal. 21 (1984) 995-1011.",
"[17] S. Clain, S. Diot, R. Loubere, A high-order finite volume method for systems of conservation laws-Multi-dimensional Optimal Order Detection (MOOD), J. Comput. Phys. 230 (2011) 4028-4050.",
"[18] S. Diot, S. Clain, R. Loubere, Improved detection criteria for the Multi-dimensional Optimal Order Detection (MOOD) on unstructured meshes with very high-order polynomials, Comput. Fluids 64 (2012) 43-63.",
"[19] Y.-X. Ren, A robust shock-capturing scheme based on rotated Riemann solvers, Comput. Fluids 32 (2003) 1379-1403.",
"[20] H. Nishikawa, K. Kitamura, Very simple, carbuncle-free, boundary-layer-resolving, rotated-hybrid Riemann solvers, J. Comput. Phys. 227 (2008) 2560-2581.",
"[21] S. Gottlieb, C.-W. Shu, E. Tadmor, Strong stability-preserving high-order time discretization methods, SIAM Rev. 43 (2001) 89-112.",
"[22] R.J. LeVeque, High-resolution conservative algorithms for advection in incompressible flow, SIAM J. Numer. Anal. 33 (1996) 627-665.",
"[23] C.W. Schulz-Rinne, J.P. Collins, H.M. Glaz, Numerical solution of the Riemann problem for two-dimensional gas dynamics, SIAM J. Sci. Comput. 14 (1993) 1394-1414.",
"[24] P.D. Lax, X.-D. Liu, Solution of two-dimensional Riemann problems of gas dynamics by positive schemes, SIAM J. Sci. Comput. 19 (1998) 319-340.",
"[25] O. Inoue, Y. Hattori, Sound generation by shock-vortex interactions, J. Fluid Mech. 380 (1999) 81-116.",
"[26] H.C. Yee, N.D. Sandham, M.J. Djomehri, Low-dissipative high-order shock-capturing methods using characteristic-based filters, J. Comput. Phys. 150 (1999) 199-238.",
"[27] P. Woodward, P. Colella, The numerical simulation of two-dimensional fluid flow with strong shocks, J. Comput. Phys. 54 (1984) 115-173.",
"[28] D. Enright, R. Fedkiw, J. Ferziger, I. Mitchell, A hybrid particle level set method for improved interface capturing, J. Comput. Phys. 183 (2002) 83-116.",
"[29] N. Hoppe, et al., Three-dimensional Riemann problems as benchmark cases for compressible-flow solvers, Comput. Fluids (2024).",
"[30] J.O. Langseth, R.J. LeVeque, A wave propagation method for three-dimensional hyperbolic conservation laws, J. Comput. Phys. 165 (2000) 126-166.",
"[31] X. Zhang, C.-W. Shu, On positivity-preserving high order discontinuous Galerkin schemes for compressible Euler equations on rectangular meshes, J. Comput. Phys. 229 (2010) 8918-8934.",
"[32] S.K. Godunov, A difference method for numerical calculation of discontinuous solutions of the equations of hydrodynamics, Mat. Sb. 47 (1959) 271-306.",
"[33] P.L. Roe, Approximate Riemann solvers, parameter vectors, and difference schemes, J. Comput. Phys. 43 (1981) 357-372.",
"[34] A. Harten, High resolution schemes for hyperbolic conservation laws, J. Comput. Phys. 49 (1983) 357-393.",
"[35] P. Colella, P.R. Woodward, The piecewise parabolic method (PPM) for gas-dynamical simulations, J. Comput. Phys. 54 (1984) 174-201.",
"[36] A. Harten, B. Engquist, S. Osher, S.R. Chakravarthy, Uniformly high order accurate essentially non-oscillatory schemes, III, J. Comput. Phys. 71 (1987) 231-303.",
"[37] G.-S. Jiang, C.-W. Shu, Efficient implementation of weighted ENO schemes, J. Comput. Phys. 126 (1996) 202-228.",
"[38] C. Hu, C.-W. Shu, Weighted essentially non-oscillatory schemes on triangular meshes, J. Comput. Phys. 150 (1999) 97-127.",
"[39] C. Michalak, C. Ollivier-Gooch, Accuracy preserving limiter for the high-order accurate solution of the Euler equations, J. Comput. Phys. 228 (2009) 8693-8711.",
"[40] M.S. Darwish, F. Moukalled, TVD schemes for unstructured grids, Int. J. Heat Mass Transfer 46 (2003) 599-611.",
"[41] M.E. Hubbard, Multidimensional slope limiters for MUSCL-type finite volume schemes on unstructured grids, J. Comput. Phys. 155 (1999) 54-74.",
"[42] J.J. Quirk, A contribution to the great Riemann solver debate, Int. J. Numer. Methods Fluids 18 (1994) 555-574.",
"[43] M. Pandolfi, D. D'Ambrosio, Numerical instabilities in upwind methods: analysis and cures for the 'carbuncle' phenomenon, J. Comput. Phys. 166 (2001) 271-301.",
"[44] D.W. Levy, K.G. Powell, B. van Leer, Use of a rotated Riemann solver for the two-dimensional Euler equations, J. Comput. Phys. 106 (1993) 201-214.",
"[45] E.F. Toro, M. Spruce, W. Speares, Restoration of the contact surface in the HLL-Riemann solver, Shock Waves 4 (1994) 25-34.",
"[46] E.F. Toro, Riemann Solvers and Numerical Methods for Fluid Dynamics: A Practical Introduction, 3rd ed., Springer, Berlin, 2009.",
"[47] B. Einfeldt, On Godunov-type methods for gas dynamics, SIAM J. Numer. Anal. 25 (1988) 294-318.",
"[48] R.J. Spiteri, S.J. Ruuth, A new class of optimal high-order strong-stability-preserving time discretization methods, SIAM J. Numer. Anal. 40 (2002) 469-491.",
"[49] S. Diot, R. Loubere, S. Clain, The Multidimensional Optimal Order Detection method in the three-dimensional case: very high-order finite volume method for hyperbolic systems, Int. J. Numer. Methods Fluids 73 (2013) 362-392.",
"[50] M. Dumbser, O. Zanotti, R. Loubere, S. Diot, A posteriori subcell limiting of the discontinuous Galerkin finite element method for hyperbolic conservation laws, J. Comput. Phys. 278 (2014) 47-75.",
"[51] B. Perthame, C.-W. Shu, On positivity preserving finite volume schemes for Euler equations, Numer. Math. 73 (1996) 119-130.",
"[52] X. Zhang, C.-W. Shu, Maximum-principle-satisfying and positivity-preserving high-order schemes for conservation laws: survey and new developments, Proc. R. Soc. A 467 (2011) 2752-2776.",
"[53] S. Ii, K. Sugiyama, S. Takeuchi, S. Takagi, Y. Matsumoto, F. Xiao, An interface capturing method with a continuous function: The THINC method with multi-dimensional reconstruction, J. Comput. Phys. 231 (2012) 2328-2358.",
"[54] K. Yokoi, Efficient implementation of THINC scheme: A simple and practical smoothed VOF algorithm, J. Comput. Phys. 226 (2007) 1985-2002.",
"[55] F. Xiao, S. Ii, C. Chen, Revisit to the THINC scheme: A simple algebraic VOF algorithm, J. Comput. Phys. 230 (2011) 7086-7092.",
"[56] S. Tann, X. Deng, Y. Shimizu, R. Loubere, F. Xiao, Solution property preserving reconstruction for finite volume scheme: a BVD+MOOD framework, Int. J. Numer. Methods Fluids 92 (2020) 603-634.",
"[57] M. Cada, M. Torrilhon, Compact third-order limiter functions for finite volume methods, J. Comput. Phys. 228 (2009) 4118-4145.",
"[58] A. Kurganov, E. Tadmor, Solution of two-dimensional Riemann problems for gas dynamics without Riemann problem solvers, Numer. Methods Partial Differ. Equ. 18 (2002) 584-608.",
"[59] S.T. Zalesak, Fully multidimensional flux-corrected transport algorithms for fluids, J. Comput. Phys. 31 (1979) 335-362."
].forEach(r => C.push(refP(r)));

const doc = new Document({
  styles: { default: { document: { run: { font: FONT, size: SZ } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal",
        run: { size: 22, bold: true, font: FONT }, paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal",
        run: { size: 20, bold: true, italics: true, font: FONT }, paragraph: { spacing: { before: 220, after: 120 }, outlineLevel: 1 } } ] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 },
    margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } }, children: C }] });

Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2] || "paper1_draft.docx", b); console.log("paper1 expanded written"); });
