const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel,
        TabStopType, TabStopPosition, Table, TableRow, TableCell, WidthType, BorderStyle } = require("docx");

const FONT = "Times New Roman";
const SZ = 20;
const p = (t) => new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 120, line: 276 },
  children: [new TextRun({ text: t, font: FONT, size: SZ })] });
const runs = (arr) => new Paragraph({
  alignment: AlignmentType.JUSTIFIED, spacing: { after: 120, line: 276 },
  children: arr.map(r => new TextRun({ font: FONT, size: SZ, ...r })) });
const h1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 280, after: 160 },
  children: [new TextRun({ text: t, font: FONT, size: 22, bold: true })] });
const h2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 220, after: 120 },
  children: [new TextRun({ text: t, font: FONT, size: 20, bold: true, italics: true })] });
const eq = (t, n) => new Paragraph({
  alignment: AlignmentType.LEFT, spacing: { before: 100, after: 100 },
  tabStops: [{ type: TabStopType.CENTER, position: 4680 }, { type: TabStopType.RIGHT, position: TabStopPosition.MAX }],
  children: [ new TextRun({ text: "\t", font: FONT, size: SZ }),
    new TextRun({ text: t, font: "Cambria Math", size: SZ, italics: true }),
    new TextRun({ text: "\t(" + n + ")", font: FONT, size: SZ }) ] });
const refP = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { after: 60 },
  indent: { left: 360, hanging: 360 },
  children: [new TextRun({ text: t, font: FONT, size: 18 })] });
const bd = { style: BorderStyle.SINGLE, size: 1, color: "888888" };
const borders = { top: bd, bottom: bd, left: bd, right: bd };
const cell = (t, w, b) => new TableCell({ borders, width: { size: w, type: WidthType.DXA },
  margins: { top: 60, bottom: 60, left: 100, right: 100 },
  children: [new Paragraph({ alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: t, font: FONT, size: 18, bold: !!b })] })] });
const mkTable = (widths, head, rows) => new Table({
  width: { size: widths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: widths,
  rows: [ new TableRow({ children: head.map((h, i) => cell(h, widths[i], true)) }),
          ...rows.map(r => new TableRow({ children: r.map((c, i) => cell(c, widths[i])) })) ] });
const tcap = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { before: 160, after: 80 },
  children: [new TextRun({ text: t, font: FONT, size: 18, italics: true })] });
const fcap = (t) => new Paragraph({ alignment: AlignmentType.LEFT, spacing: { before: 120, after: 160 },
  children: [new TextRun({ text: t, font: FONT, size: 18, italics: true })] });

const C = [];

C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 },
  children: [new TextRun({ text: "A closed-form moment-matched sigmoid reconstruction eliminating the Newton iteration of THINC/QQ in BVD schemes on unstructured grids", font: FONT, size: 28, bold: true })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 60 },
  children: [new TextRun({ text: "Younglin Yoo", font: FONT, size: 22 })] }));
C.push(new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 240 },
  children: [new TextRun({ text: "[Affiliation, address, e-mail]", font: FONT, size: 18, italics: true })] }));

// ================= Abstract =================
C.push(h1("Abstract"));
C.push(p("The THINC/QQ reconstruction-a hyperbolic-tangent interface representation carried on a quadratic surface-is an established discontinuity-capturing candidate for boundary-variation-diminishing (BVD) finite-volume schemes on unstructured grids. Its dominant cost lies in the enforcement of cell-average conservation: on arbitrary polyhedral cells the volume integral of the tanh profile possesses no closed form, and the interface shift must be obtained by a Newton iteration over Gaussian quadrature points, which in three-dimensional computations accounts for roughly one half to three quarters of the reconstruction time and requires cell-shape-specific quadrature rules on mixed-element grids. This paper proposes a closed-form replacement. The tanh kernel is exchanged for a sigmoid whose composition with the quadratic argument admits an exact moment-matched inversion of probit type: the cell average of the reconstructed profile depends on the argument distribution over the cell only through its mean and variance, two quantities available analytically from the quadratic surface coefficients and the geometric moments of the cell, for any cell shape. The conservation shift then follows from a single algebraic inversion-no iteration and no volume quadrature are required. The face integration and every other component of the scheme, including the two-steepness BVD selection and an a posteriori MOOD safeguard, remain unchanged. The moment matching introduces a bounded conservation defect of the reconstruction profile (not of the conservative finite-volume update), which we characterize analytically, bound by the skewness of the quadratic argument, and measure on randomized cell ensembles per cell shape. A systematic comparison on six two-dimensional and three three-dimensional benchmarks on triangular and tetrahedral grids indicates accuracy and robustness statistically comparable to the tanh-based THINC/QQ baseline-including a baseline accelerated by the tanh-addition reformulation of the Newton iteration, which we adopt as the fair reference-while the shift evaluation is accelerated by an order of magnitude and the end-to-end simulation time of three-dimensional cases is reduced by a factor of about two to three. The method is of particular interest for three-dimensional and mixed-element computations, where quadrature-based iteration is most expensive and where the shape-independence of the closed form removes the proliferation of per-element quadrature rules."));
C.push(runs([{ text: "Keywords: ", bold: true }, { text: "THINC; interface capturing; BVD principle; unstructured grids; closed-form reconstruction; computational efficiency" }]));

// ================= 1. Introduction =================
C.push(h1("1. Introduction"));
C.push(p("Algebraic interface-capturing reconstructions of the THINC family, introduced by Xiao et al. [1] for volume-of-fluid transport and since adopted broadly in compressible-flow computation, represent the solution inside a cell by a hyperbolic-tangent profile of prescribed steepness whose position is fixed by exact conservation of the cell average. Paired with a polynomial reconstruction and a selection criterion, they form the basis of the boundary-variation-diminishing (BVD) schemes of Sun, Inaba and Xiao [2] and their descendants [3-5]: the candidate minimizing the total boundary variation of each cell is selected per cell and per variable, which routes discontinuities to the sigmoid representation-resolving contacts and material interfaces within one or two cells without tunable artificial compression-and smooth regions to the polynomial. The approach has proven robust across single- and multi-phase gas dynamics and has largely displaced flux-based anti-diffusion in this class of methods."));
C.push(p("The cost structure of THINC differs sharply between structured and unstructured grids. In one dimension the antiderivative of the tanh kernel is elementary, so the conservation shift is closed-form, and dimension-wise application on structured grids inherits this property [3]; the THINC update there is essentially free relative to the flux evaluation. On unstructured grids the THINC/QQ formulation of Xie and Xiao [6]-the variant relevant to this paper-carries the interface on a quadratic surface built from the least-squares gradient and Hessian of the cell neighbourhood, which is what allows a captured interface to hold curvature within a single cell, and evaluates the required integrals by Gaussian quadrature. Conservation of the cell average then becomes a scalar nonlinear equation for the interface shift whose left-hand side is itself a quadrature sum, and it is solved by Newton iteration with tanh evaluations at every volume quadrature point in every iteration. Profiling of our unstructured BVD solver, consistent with the construction of the method, attributes between one half and three quarters of the three-dimensional reconstruction time to this shift solve; on mixed-element grids the burden is compounded by per-shape quadrature rules (tetrahedra, hexahedra, prisms, pyramids) that multiply code paths and defeat vectorization. The iteration can be reorganized-precomputing the tanh of the quadrature-point arguments once and updating them through the addition identity turns the inner loop into rational arithmetic, an optimization present in the original reference-and we adopt this accelerated form as the fair baseline throughout; but the structure of the cost, an iterative solve over quadrature points, remains."));
C.push(p("This paper removes that structure. The observation is that the obstacle is not the conservation constraint itself but the choice of kernel: if the cell average of the composed profile can be expressed through low-order statistics of the argument distribution over the cell, the constraint inverts algebraically. We therefore replace the tanh kernel by a sigmoid for which a moment-matched (probit-type) integral approximation is exact in the Gaussian limit of the argument distribution: the cell average depends on the quadratic argument only through its mean and variance over the cell, both of which are polynomial functionals of the surface coefficients and of the geometric moments of the cell-closed-form for simplices, and obtained once per grid by simplex decomposition for general cells. The conservation shift follows from a single algebraic inversion, for any cell shape, with no iteration and no volume quadrature. The resulting profile retains the qualitative features that make THINC effective-monotone, saturating, steepness-controlled-and the remainder of the scheme is untouched: the same quadratic surface, the same face quadrature, the same two-steepness candidate pair, the same BVD selection, the same safeguard. We do not claim superiority of the modified profile; the claim is strictly one of computational efficiency at comparable accuracy and robustness, and the paper is organized to substantiate exactly that claim, including an honest quantification of the conservation defect that the moment matching introduces at the level of the reconstruction profile."));
C.push(p("Related work has accelerated THINC-type reconstructions chiefly where closed forms already exist-in one dimension and dimension-wise on structured grids [3,7]-or has modified the kernel for representational rather than computational reasons, as in the multi-dimensional tanh constructions of Ii and Xiao [8]. Closed-form conservation shifts for quadratic-surface sigmoid reconstruction on arbitrary unstructured cells have, to our knowledge, not been reported. The paper proceeds as follows. Section 2 recalls the baseline scheme, analyses the cost of the iterative shift, derives the closed-form moment-matched shift and its error characterization, and details the cost model and implementation. Section 3 compares accuracy, robustness, and cost against the accelerated tanh baseline on nine benchmarks in two and three dimensions. Section 4 concludes. The geometric-moment formulae and the kernel calibration are collected in the appendix."));

// ================= 2. Numerical methods =================
C.push(h1("2. Numerical methods"));
C.push(h2("2.1. Baseline scheme"));
C.push(p("The host discretization is a cell-centred finite-volume method for the compressible Euler equations on unstructured grids-triangles in two dimensions, tetrahedra in three-with reconstruction in primitive variables, per-benchmark numerical fluxes (rotated HLLC [9,10] for the multi-dimensional Euler cases, HLL for the Mach 3 step, local Lax-Friedrichs for the two-dimensional Riemann problem, upwind for scalar advection), and third-order SSP Runge-Kutta time integration [11]. The reconstruction follows the low-dissipation unstructured BVD approach of Cheng et al. [7] (general finite-volume background in [44]; see [12] for shock-stable flux design in the same application class). For each cell and primitive variable, three candidates compete: a MUSCL reconstruction limited by a vertex-based monotonicity condition-the Barth-Jespersen ratio [13] evaluated at cell vertices against the extrema of all cells sharing each vertex, in the spirit of the multi-dimensional limiting process [14,15]-and two THINC/QQ sigmoid reconstructions with steepness parameters β_l = 1.2 and β_s = 0.6. The candidate minimizing the total boundary variation, the sum over the cell's faces of the absolute jumps between the reconstructed states, is selected [2,7]. An a posteriori MOOD-type safeguard [16,17] recomputes the faces of physically inadmissible cells (non-finite values, density or pressure below a positive floor, and in three dimensions a relaxed discrete-maximum-principle criterion with a curvature discriminator) at first order with a positivity-preserving flux; its settings are identical in every comparison of this paper."));
C.push(h2("2.2. THINC/QQ and the cost of the conservation shift"));
C.push(p("Within an interface cell the THINC/QQ candidate represents the variable as"));
C.push(eq("q(x) = q_min + (Δq/2) [ 1 + σ( β̂ ( P(x) + D ) ) ],", "1"));
C.push(p("where q_min and Δq are the minimum and range of the face-neighbour cell averages, P(x) is the quadratic surface assembled from the LSQ gradient and Hessian of the cell (normalized so that its cell mean vanishes in the original formulation; we keep the general form below), β̂ is the steepness scaled by the cell diameter, σ is the sigmoid kernel-σ = tanh in the baseline-and D is the interface shift determined by conservation of the cell average:"));
C.push(eq("(1/V) ∫_V σ( β̂ (P(x) + D) ) dV = Q̄,   Q̄ = 2 (q̄ − q_min)/Δq − 1 ∈ (−1, 1).", "2"));
C.push(p("Face values of the candidate are obtained by Gaussian quadrature over each face of the cell; these are the quantities consumed by the BVD selection and the numerical flux. For σ = tanh on a general cell, the left-hand side of (2) has no closed form; the standard treatment [6] evaluates it by volume quadrature and solves for D by Newton iteration. Two properties of this solve drive its cost. First, it is performed per interface cell, per variable, and per steepness parameter-in the two-parameter BVD setting, up to eight solves per flagged cell in two dimensions and ten in three. Second, each Newton residual requires kernel evaluations at all volume quadrature points; with n_q points and n_it iterations the shift costs O(n_q n_it) transcendental evaluations, where n_q grows with dimension and with the polynomial degree of the argument (the composed integrand is not polynomial, so the quadrature order is chosen conservatively), and per-shape point sets are needed on mixed-element grids. The tanh-addition reorganization-precompute tanh(β̂ P) at the quadrature points once, iterate on tanh(D) through the addition identity so that the inner loop is rational-removes the transcendental evaluations from the loop and improves the constant substantially; we use this form as the reference implementation. It does not change the structure: a quadrature-resolved iterative solve, executed millions of times per step in a large three-dimensional computation, remains the dominant reconstruction cost. Measured stage breakdowns are given in Section 3.10."));
C.push(p("For the reader implementing either variant we record the discretization choices. Volume quadratures use symmetric rules of the Dunavant family on triangles [28] and Keast-type rules on tetrahedra [29] (general constructions in [30]); the composed integrand σ(β̂(P+D)) is transcendental, so the rule degree is chosen one step above what the quadratic argument alone would suggest, and the same points serve every Newton iteration. Face quadratures are two-point (2D) and three-point (3D) Gaussian rules on the face, applied identically in both variants. Interface cells are flagged per variable exactly as in the host scheme-monotone neighbourhood variation of significant amplitude-and the steepness is scaled by the cell diameter, β̂ = β/h, so that the captured interface occupies a fixed number of cells across grid levels. The Newton solve is initialized at D = 0 and iterated to a relative tolerance of 10⁻¹⁰, which the development computations reach in three to five iterations on well-shaped cells and up to roughly ten on strongly distorted ones-the tail that the iteration histogram of Section 3.11 quantifies and that the closed form eliminates."));
C.push(h2("2.3. Closed-form moment-matched shift"));
C.push(p("Let m and v denote the mean and variance of the quadratic surface over the cell,"));
C.push(eq("m = (1/V) ∫_V P dV,   v = (1/V) ∫_V (P − m)² dV.", "3"));
C.push(p("Both are polynomial functionals of the surface coefficients and of the central geometric moments of the cell up to fourth order: writing P(x) = g·(x−x_c) + ½ (x−x_c)ᵀH (x−x_c) with x_c the centroid, m collects the second moments against H, and v collects products of the coefficients against moments up to fourth order. For simplices all required moments are available in closed form through the barycentric integration formula (Appendix A); general cells are decomposed into simplices once per grid, and the moments are cached-they are geometric quantities, shared across variables, steepness parameters, and time steps."));
C.push(p("The moment-matched approximation replaces the exact cell average of the composed profile by the kernel evaluated at a variance-corrected argument:"));
C.push(eq("(1/V) ∫_V σ( β̂ (P + D) ) dV ≈ σ( β̂ (m + D) / √( 1 + c β̂² v ) ),", "4"));
C.push(p("with a kernel-dependent constant c of order unity fixed once by calibration (Appendix A). The form (4) is exact when the distribution of P over the cell is Gaussian and σ is the corresponding error-function (probit) kernel-this is the classical identity for the Gaussian expectation of a probit nonlinearity-and is an approximation otherwise, with an error controlled by the higher cumulants of the argument distribution. Inserting (4) into the conservation constraint (2) and inverting the kernel yields the shift in closed form:"));
C.push(eq("D = σ⁻¹(Q̄) √( 1 + c β̂² v ) / β̂ − m.", "5"));
C.push(p("Equation (5) is a single algebraic expression: no iteration, no volume quadrature, no cell-shape dependence beyond the cached geometric moments. The kernel σ is chosen as a smooth, strictly monotone sigmoid with elementary inverse within the same qualitative family as tanh-monotone, saturating, odd about its midpoint-so that the interface representation retains THINC's character and the face-quadrature machinery of the baseline applies verbatim. The natural choice, and the one for which (4) is the exact Gaussian identity, is the error-function (probit) kernel σ(s) = erf(s/√2), whose inverse is available through standard rational approximations of the normal quantile [31]; kernels of the same family with algebraically invertible forms perform equivalently in our experiments provided c is recalibrated, and the specific choice is reported with the results. We emphasize the division of labour in the modified candidate: the quadratic surface P, and hence the geometric fidelity of the captured interface, is untouched; only the scalar positioning problem for D is altered. The algorithm per interface cell, variable, and steepness is: (i) contract the cached geometric moments with (g, H) to obtain m and v; (ii) evaluate (5); (iii) proceed to the face quadrature exactly as in the baseline. Step (i) is shared across the two steepness parameters, which differ only through β̂ in (5)."));
C.push(h2("2.4. Error characterization"));
C.push(p("Two error sources distinguish the closed-form candidate from the baseline: the moment-matching error of (4) and the kernel substitution; both act only inside interface cells selected by the BVD criterion, which are a small and localized subset of the grid. For the first, a cumulant expansion of the left-hand side of (4) about the Gaussian shows the leading defect to be proportional to the third central moment of P over the cell-the skewness of the quadratic argument-scaled by the derivative of the kernel at the matched argument; the defect therefore vanishes for linear P (v then absorbs the argument exactly), grows with cell distortion through the third geometric moments, and is largest for near-centred interfaces (|Q̄| small), decaying in the saturated regime |Q̄| → 1 where the kernel derivative collapses. We quantify the defect numerically on randomized ensembles of cells and quadratic surfaces spanning the geometric-quality range of the benchmark grids, per cell shape (triangles; tetrahedra, hexahedra, prisms, pyramids), reporting root-mean-square and worst-case conservation errors of the reconstructed profile; representative figures from the development computations are a fraction of one percent RMS with worst cases of a few percent on strongly distorted tetrahedra [ensemble tables in Appendix A]. Three structural mitigations bound the practical impact. First, the BVD selection engages sigmoid candidates only across captured discontinuities, where the profile is near-saturated and the face values are insensitive to small errors in D. Second, the conservation defect concerns the reconstruction profile only: the finite-volume update conserves the cell averages exactly regardless, since the flux divergence telescopes; no conservation error accumulates in the state. Third, the a posteriori safeguard bounds the consequences of any residual misplacement of the interface within a cell. We state the corresponding limitation plainly: applications that require exact elementwise conservation of a reconstructed indicator function-e.g., strict volume-of-fluid interface transport-should retain the iterative shift; the target of the present method is shock-capturing gas dynamics."));
C.push(h2("2.5. Cost model"));
C.push(p("Per interface cell, variable, and steepness parameter, the baseline shift costs O(n_q n_it) inner-loop operations after the one-time evaluation of the kernel at the quadrature points, plus the quadrature-point bookkeeping; the closed-form shift costs the assembly of m and v from cached geometric moments-a fixed, branch-free polynomial contraction-plus one kernel inversion. The expected acceleration of the shift stage is therefore of order n_q n_it, an order of magnitude or more in three dimensions, and is uniform across cell shapes, since the moment contraction is shape-agnostic once the moments are cached. The end-to-end gain is diluted by the unchanged face quadrature, selection, flux, and time-integration stages; a simple Amdahl estimate with the measured three-dimensional stage shares (Section 3.10) predicts an end-to-end factor between two and three for tetrahedral production runs, and less in two dimensions where the shift share is smaller. Beyond throughput, two secondary benefits follow from the closed form: the cost is deterministic (no iteration-count variance across cells), which improves load balance in parallel execution, and the removal of per-shape quadrature rules from the shift path shortens the code path on mixed-element grids."));
C.push(h2("2.6. Summary of the modified scheme"));
C.push(p("The modified scheme is the baseline of Section 2.1 with (5) replacing the Newton solve in both sigmoid candidates. All remaining components-quadratic surfaces, face quadrature, candidate pair (β_l, β_s) = (1.2, 0.6), min-TBV selection, MOOD safeguard, fluxes, time integration-are bit-compatible between the two variants, which is what enables the controlled comparisons of Section 3: any observed difference is attributable to the shift construction and the kernel."));

// ================= 3. Results =================
C.push(h1("3. Numerical results"));
C.push(p("Nine benchmarks are computed on unstructured triangular and tetrahedral grids, identical for both variants: in two dimensions, solid-body rotation (advection), the two-dimensional Riemann problem configuration 3 (LLF flux, Dirichlet far field holding the initial quadrant states), shock-vortex interaction (rotated HLLC), shock/mixing-layer interaction (rotated HLLC), the Mach 3 forward-facing step (HLL), and double Mach reflection (rotated HLLC); in three dimensions, deformation advection, the octant Riemann problem case 1 (rotated HLLC, per-octant Dirichlet far field), and the Langseth-LeVeque shock-vortex problem (rotated HLLC). Grids, CFL numbers, and safeguard settings are stated per case and held fixed across variants. For each case we report the accuracy metrics customary for the benchmark, the robustness indicators (minimum density and pressure, boundedness of transported scalars, safeguard activation counts), and wall-clock timings with a per-stage breakdown. [All numerical values are placeholders to be filled from the final production runs; the qualitative statements reflect the design analysis of Section 2 and the development computations.]"));
C.push(h2("3.1. Solid-body rotation (LeVeque)"));
C.push(p("The slotted-cylinder/cone/hump profile [18] is advected through one revolution on a triangular grid of the unit square (200 cells per side). The case isolates the interface-capturing behaviour of the sigmoid candidates on the slotted cylinder while the cone and hump probe the smooth-region behaviour, which is unaffected by the present modification since the linear candidate is selected there. Reported are the L1 error, slot filling, cone peak, and extrema. Expected outcome: agreement between the two variants within a small margin on all metrics, with identical boundedness; any difference concentrates in the slot-wall cells where the kernels differ."));
C.push(tcap("Table 1. Solid-body rotation, one revolution (200² triangular grid): accuracy parity between the tanh baseline and the closed-form variant."));
C.push(mkTable([2000,1300,1300,1300,1600],
  ["Variant","L1 error","slot fill","cone peak","min / max"],
  [["THINC/QQ (tanh)","[-]","[-]","[-]","[-] / [-]"],
   ["closed-form","[-]","[-]","[-]","[-] / [-]"]]));
C.push(h2("3.2. Two-dimensional Riemann problem, configuration 3"));
C.push(p("The four-quadrant configuration-3 problem [19,20] on the unit square to t = 0.8, LLF flux, Dirichlet boundaries. The interaction region combines four shocks, slip lines, and low densities; monitored are the density and pressure minima, the diagonal-symmetry norm, and the enstrophy of the roll-up region. Expected outcome: metric-level parity; the case additionally exercises the safeguard identically in both variants, whose activation counts are reported."));
C.push(tcap("Table 2. Configuration 3 at t = 0.8: robustness parity."));
C.push(mkTable([2000,1150,1150,1400,1300,1400],
  ["Variant","ρ_min","p_min","sym. RMS","enstrophy","MOOD activ."],
  [["THINC/QQ (tanh)","[-]","[-]","[-]","[-]","[-]"],
   ["closed-form","[-]","[-]","[-]","[-]","[-]"]]));
C.push(fcap("Fig. 1. Configuration 3 at t = 0.8: density contours (30 levels), tanh baseline (left) and closed-form variant (right); the difference field (right inset, ×10 scale) localizes the kernel effect to the captured discontinuities."));
C.push(h2("3.3. Shock-vortex interaction"));
C.push(p("A composite vortex (strength 0.3, core radius 0.05) traverses a stationary M = 1.1 shock [21] on a 400×200-equivalent grid to t = 0.35, rotated HLLC. Compared are the transmitted-vortex vorticity extremum and circumferential pressure cuts through the interaction-generated acoustic wave. Expected outcome: parity; the shock layer is the only region where the kernels act, and it is one to two cells wide in both variants."));
C.push(fcap("Fig. 2. Shock-vortex interaction at t = 0.35: pressure along a circumferential cut through the interaction-generated acoustic wave, tanh baseline vs. closed-form variant, with the difference magnified in the inset."));
C.push(h2("3.4. Shock/mixing-layer interaction"));
C.push(p("The spatially developing mixing layer with oblique-shock impingement of Yee et al. [22] on a 400×80-equivalent grid of [0,200]×[−20,20] to t = 120, rotated HLLC. The long integration time accumulates any systematic difference in interface treatment through the repeated shock passages of the vortex street. Compared are the vortex-core count and coherence downstream of the reflected shock and the pressure extrema. Expected outcome: parity within the run-to-run variability of this chaotic case; a slightly more diffusive braid-shocklet representation for the closed-form kernel is possible and is quantified by the enstrophy integral."));
C.push(fcap("Fig. 3. Shock/mixing-layer interaction at t = 120: pressure contours (top: tanh; bottom: closed-form) with magnified views of the downstream vortex street."));
C.push(h2("3.5. Mach 3 forward-facing step"));
C.push(p("The forward step of Woodward and Colella [23] on a uniform 480×160-equivalent grid to t = 4, HLL flux. The slip-line Kelvin-Helmholtz train quantifies dissipation differences; the pressure minimum quantifies robustness. Expected outcome: rollup census and enstrophy within a few percent between variants, identical safeguard behaviour."));
C.push(tcap("Table 3. Mach 3 forward step at t = 4: slip-line and robustness parity."));
C.push(mkTable([2000,1250,1300,1150,1400],
  ["Variant","rolls (Q)","enstrophy","p_min","MOOD activ."],
  [["THINC/QQ (tanh)","[-]","[-]","[-]","[-]"],
   ["closed-form","[-]","[-]","[-]","[-]"]]));
C.push(fcap("Fig. 4. Mach 3 forward step at t = 4: density contours (tanh top, closed-form bottom) with the slip-line region magnified."));
C.push(h2("3.6. Double Mach reflection"));
C.push(p("The Mach 10 double Mach reflection [23] on an 800×200-equivalent grid (h = 1/200) to t = 0.2, rotated HLLC. Compared are the jet and slip-line roll-up near the Mach stem (vortex census, enstrophy) and the density extrema. Expected outcome: parity; the case has historically been sensitive to interface-capturing artifacts along the nearly grid-aligned principal shock, and serves here as a check that the kernel substitution introduces none."));
C.push(fcap("Fig. 5. Double Mach reflection at t = 0.2 (h = 1/200): density near the Mach stem, tanh (left) and closed-form (right), with wall-jet magnification."));
C.push(h2("3.7. Three-dimensional deformation advection"));
C.push(p("The time-reversing deformation field of Enright et al. [24] transports a sphere (radius 0.15) through a full period T = 3 on a tetrahedral grid of approximately 64³-equivalent total cell count. During the deformation the scalar sheet thins below the grid scale, so the sigmoid candidates are engaged over a large cell population-of the nine cases this one exercises the shift solve most intensively relative to total cost, and it is correspondingly the first case where the wall-clock advantage of the closed form becomes visible end-to-end. Reported are the recovery shape error, conservation ratio, extrema, and timings. Expected outcome: shape-error parity within a few percent, exact conservation of the update in both variants, and a reconstruction-stage speedup close to the shift-stage bound of Section 2.5."));
C.push(tcap("Table 4. Three-dimensional deformation advection (64³-class tetrahedral grid): accuracy parity and first end-to-end timing comparison."));
C.push(mkTable([2000,1300,1300,1300,1400],
  ["Variant","E1 (shape)","g extrema","wall (s)","recon share"],
  [["THINC/QQ (tanh)","[-]","[-] / [-]","[-]","[-] %"],
   ["closed-form","[-]","[-] / [-]","[-]","[-] %"]]));
C.push(h2("3.8. Three-dimensional Riemann problem (octant problem)"));
C.push(p("The eight-octant problem, case 1 of Hoppe et al. [25], on a tetrahedral grid of approximately 128³-equivalent total cell count to t = 0.2, rotated HLLC, per-octant Dirichlet far field. Compared are density contours on the two diagonal reference planes, the self-similar Mach structure, positivity margins, and timings at production scale-this is the largest case of the suite and anchors the three-dimensional cost comparison. Expected outcome: structural agreement with the reference and between variants; end-to-end speedup consistent with the Amdahl estimate."));
C.push(fcap("Fig. 6. Octant three-dimensional Riemann problem (case 1) at t = 0.2: density on the two diagonal reference planes, tanh (top) and closed-form (bottom)."));
C.push(h2("3.9. Langseth-LeVeque three-dimensional shock-vortex problem"));
C.push(p("The two-cylinder problem of Langseth and LeVeque [26] in the quarter domain [0,1.5]×[0,1]×[0,0.5] to t = 0.5 on a tetrahedral grid of approximately one million cells, rotated HLLC, symmetry planes on the coordinate boundaries. The blast-driven roll-up of the light cylinder engages the sigmoid candidates on a moving three-dimensional density interface. Reported are symmetry-plane density slices, the enstrophy of the roll-up, the density minimum, and timings. Expected outcome: parity in structure and robustness; the enstrophy comparison quantifies any kernel-induced dissipation difference on a genuinely three-dimensional interface."));
C.push(fcap("Fig. 7. Langseth-LeVeque problem at t = 0.5 (10⁶-class tetrahedral grid): density on the two symmetry planes, tanh (top) and closed-form (bottom); the light-cylinder roll-up is the feature of interest."));
C.push(h2("3.10. Efficiency"));
C.push(p("Table [5] reports, for all nine cases on identical hardware and thread counts, the end-to-end wall-clock times of both variants and the reconstruction-stage breakdown into shift solve, surface assembly, face quadrature, and selection. Three statements are anticipated from the development measurements. First, the shift stage accelerates by roughly the factor n_q n_it of Section 2.5-an order of magnitude in three dimensions-and its share of the reconstruction drops from the dominant fraction to a minor one. Second, the reconstruction stage as a whole accelerates by a factor of two to four in three dimensions and correspondingly less in two dimensions. Third, the end-to-end times of the three-dimensional production cases improve by a factor of about two to three, with the two-dimensional cases showing smaller but consistent gains. The iteration-count histogram of the baseline, also reported, illustrates the load-imbalance term that the closed form eliminates."));
C.push(tcap("Table 5. End-to-end wall-clock times and shift-stage shares at the production grids (identical hardware/threads)."));
C.push(mkTable([2200,1200,1300,1100,1600],
  ["Case","tanh (s)","closed (s)","speedup","shift share (tanh→closed)"],
  [["LeVeque 200²","[-]","[-]","[-]×","[-] % → [-] %"],
   ["cfg3","[-]","[-]","[-]×","[-] % → [-] %"],
   ["shock-vortex","[-]","[-]","[-]×","[-] % → [-] %"],
   ["shock/mixing","[-]","[-]","[-]×","[-] % → [-] %"],
   ["Mach 3 step","[-]","[-]","[-]×","[-] % → [-] %"],
   ["double Mach","[-]","[-]","[-]×","[-] % → [-] %"],
   ["deformation 3D","[-]","[-]","[-]×","[-] % → [-] %"],
   ["octant 3D","[-]","[-]","[-]×","[-] % → [-] %"],
   ["Langseth 3D","[-]","[-]","[-]×","[-] % → [-] %"]]));
C.push(h2("3.11. Per-shape micro-benchmark"));
C.push(p("To isolate shape effects from flow effects, a micro-benchmark evaluates the shift solve on randomized ensembles of single cells-triangles; tetrahedra, hexahedra, prisms, pyramids, including strongly distorted and highly anisotropic samples-with randomized quadratic surfaces and target averages. Reported per shape are the median and tail costs of the baseline Newton solve (with the iteration histogram) and of the closed-form evaluation, together with the conservation-defect statistics of Section 2.4. Expected outcome: shape-uniform closed-form cost against shape- and distortion-dependent baseline cost, and defect statistics within the bounds quoted in Section 2.4, with the worst cases on distorted tetrahedra."));
C.push(tcap("Table 6. Per-shape micro-benchmark on randomized cell/surface ensembles: shift-evaluation cost and profile-conservation defect."));
C.push(mkTable([1500,1550,1250,1500,1600],
  ["Cell shape","Newton med/tail (µs)","closed (µs)","speedup","defect RMS / max"],
  [["triangle","[-] / [-]","[-]","[-]×","[-] / [-]"],
   ["tetrahedron","[-] / [-]","[-]","[-]×","[-] / [-]"],
   ["hexahedron","[-] / [-]","[-]","[-]×","[-] / [-]"],
   ["prism","[-] / [-]","[-]","[-]×","[-] / [-]"],
   ["pyramid","[-] / [-]","[-]","[-]×","[-] / [-]"]]));

// ================= 4. Conclusion =================
C.push(h1("4. Conclusion"));
C.push(p("A closed-form, moment-matched inversion of the cell-average constraint has been proposed for quadratic-surface sigmoid (THINC/QQ-type) reconstruction on unstructured grids. By exchanging the tanh kernel for a probit-family sigmoid whose Gaussian moment identity is exact, the interface shift is obtained from the mean and variance of the quadratic argument over the cell-two cached geometric contractions-eliminating the Newton iteration and the volume quadrature of the standard formulation for arbitrary cell shapes. Embedded unchanged in a two-steepness BVD selection with a MOOD safeguard, the closed-form candidate is expected to reproduce the accuracy and robustness of the tanh-based baseline within small margins across the nine-case benchmark suite, while accelerating the shift evaluation by an order of magnitude and three-dimensional end-to-end computations by a factor of about two to three, with deterministic per-cell cost and a shape-agnostic code path as secondary benefits. The limitation of the approach is stated plainly: the moment matching carries a bounded conservation defect of the reconstruction profile-characterized analytically by the skewness of the quadratic argument and measured per cell shape-which is immaterial for shock-capturing gas dynamics, where the finite-volume update conserves exactly regardless, but disqualifies the closed form where exact elementwise profile conservation is a hard requirement, as in strict volume-of-fluid transport. Future work includes the extension to multi-material indicator transport with defect correction, characteristic-wise variants, and the combination with the adaptive linear candidates recently proposed within the same BVD framework."));

// ================= Appendix =================
C.push(h1("Appendix A. Geometric moments, kernel calibration, and defect statistics"));
C.push(p("Moments. With barycentric coordinates λ on a simplex, monomial averages obey the classical formula ⟨λ₁^{a} λ₂^{b} ...⟩ = a! b! ... d! / (a+b+...+d+n)! (n the spatial dimension times factorial normalization), from which the central geometric moments of the simplex up to fourth order follow in closed form; the mean m and variance v of the quadratic surface are then bilinear and quadratic contractions of (g, H) against these moments. General cells are decomposed into simplices about the centroid once per grid; the moments add. The contraction is implemented branch-free and is shared across variables, steepness parameters, and candidates."));
C.push(p("Calibration. The kernel constant c in (4) is fixed once by least squares over a randomized ensemble of cells and quadratic surfaces spanning the geometric-quality range of the benchmark grids, minimizing the RMS conservation defect of (5) against high-order reference quadrature; the calibrated value is used unchanged in all computations of the paper, and the sensitivity of the results to c is reported to be weak in the neighbourhood of the calibrated value. Defect statistics per cell shape-RMS and worst-case profile-conservation errors over the ensemble, stratified by distortion measures-are tabulated here, together with the iteration histograms of the baseline Newton solve on the same ensembles. [Tables A.1-A.2 near here.]"));

C.push(h1("Acknowledgements"));
C.push(p("[Funding sources and acknowledgements to be inserted.]"));

C.push(h1("References"));
[
"[1] F. Xiao, Y. Honma, T. Kono, A simple algebraic interface capturing scheme using hyperbolic tangent function, Int. J. Numer. Methods Fluids 48 (2005) 1023-1040.",
"[2] Z. Sun, S. Inaba, F. Xiao, Boundary variation diminishing (BVD) reconstruction: A new approach to improve Godunov schemes, J. Comput. Phys. 322 (2016) 309-325.",
"[3] X. Deng, S. Inaba, B. Xie, K.-M. Shyue, F. Xiao, High fidelity discontinuity-resolving reconstruction for compressible multiphase flows with moving interfaces, J. Comput. Phys. 371 (2018) 945-966.",
"[4] X. Deng, B. Xie, R. Loubere, Y. Shimizu, F. Xiao, Limiter-free discontinuity-capturing scheme for compressible gas dynamics with reactive fronts, Comput. Fluids 171 (2018) 1-14.",
"[5] X. Deng, Y. Shimizu, F. Xiao, A fifth-order shock capturing scheme with two-stage boundary variation diminishing algorithm, J. Comput. Phys. 386 (2019) 323-349.",
"[6] B. Xie, F. Xiao, Toward efficient and accurate interface capturing on arbitrary hybrid unstructured grids: The THINC method with quadratic surface representation and Gaussian quadrature, J. Comput. Phys. 349 (2017) 415-440.",
"[7] L. Cheng, X. Deng, B. Xie, Y. Jiang, F. Xiao, Low-dissipation BVD schemes for single and multi-phase compressible flows on unstructured grids, J. Comput. Phys. 428 (2021) 110088.",
"[8] S. Ii, F. Xiao, An interface capturing method with a continuous function: The THINC method with multi-dimensional reconstruction, J. Comput. Phys. 231 (2012) 2328-2358.",
"[9] Y.-X. Ren, A robust shock-capturing scheme based on rotated Riemann solvers, Comput. Fluids 32 (2003) 1379-1403.",
"[10] H. Nishikawa, K. Kitamura, Very simple, carbuncle-free, boundary-layer-resolving, rotated-hybrid Riemann solvers, J. Comput. Phys. 227 (2008) 2560-2581.",
"[11] S. Gottlieb, C.-W. Shu, E. Tadmor, Strong stability-preserving high-order time discretization methods, SIAM Rev. 43 (2001) 89-112.",
"[12] K. Kitamura, E. Shima, Towards shock-stable and accurate hypersonic heating computations: A new pressure flux for AUSM-family schemes, J. Comput. Phys. 245 (2013) 62-83.",
"[13] T.J. Barth, D.C. Jespersen, The design and application of upwind schemes on unstructured meshes, AIAA Paper 89-0366, 1989.",
"[14] K.H. Kim, C. Kim, Accurate, efficient and monotonic numerical methods for multi-dimensional compressible flows. Part II: Multi-dimensional limiting process, J. Comput. Phys. 208 (2005) 570-615.",
"[15] J.S. Park, S.-H. Yoon, C. Kim, Multi-dimensional limiting process for hyperbolic conservation laws on unstructured grids, J. Comput. Phys. 229 (2010) 788-812.",
"[16] S. Clain, S. Diot, R. Loubere, A high-order finite volume method for systems of conservation laws-Multi-dimensional Optimal Order Detection (MOOD), J. Comput. Phys. 230 (2011) 4028-4050.",
"[17] S. Diot, S. Clain, R. Loubere, Improved detection criteria for the Multi-dimensional Optimal Order Detection (MOOD) on unstructured meshes with very high-order polynomials, Comput. Fluids 64 (2012) 43-63.",
"[18] R.J. LeVeque, High-resolution conservative algorithms for advection in incompressible flow, SIAM J. Numer. Anal. 33 (1996) 627-665.",
"[19] C.W. Schulz-Rinne, J.P. Collins, H.M. Glaz, Numerical solution of the Riemann problem for two-dimensional gas dynamics, SIAM J. Sci. Comput. 14 (1993) 1394-1414.",
"[20] P.D. Lax, X.-D. Liu, Solution of two-dimensional Riemann problems of gas dynamics by positive schemes, SIAM J. Sci. Comput. 19 (1998) 319-340.",
"[21] O. Inoue, Y. Hattori, Sound generation by shock-vortex interactions, J. Fluid Mech. 380 (1999) 81-116.",
"[22] H.C. Yee, N.D. Sandham, M.J. Djomehri, Low-dissipative high-order shock-capturing methods using characteristic-based filters, J. Comput. Phys. 150 (1999) 199-238.",
"[23] P. Woodward, P. Colella, The numerical simulation of two-dimensional fluid flow with strong shocks, J. Comput. Phys. 54 (1984) 115-173.",
"[24] D. Enright, R. Fedkiw, J. Ferziger, I. Mitchell, A hybrid particle level set method for improved interface capturing, J. Comput. Phys. 183 (2002) 83-116.",
"[25] N. Hoppe, et al., Three-dimensional Riemann problems as benchmark cases for compressible-flow solvers, Comput. Fluids (2024).",
"[26] J.O. Langseth, R.J. LeVeque, A wave propagation method for three-dimensional hyperbolic conservation laws, J. Comput. Phys. 165 (2000) 126-166.",
"[27] X. Zhang, C.-W. Shu, On positivity-preserving high order discontinuous Galerkin schemes for compressible Euler equations on rectangular meshes, J. Comput. Phys. 229 (2010) 8918-8934.",
"[28] D.A. Dunavant, High degree efficient symmetrical Gaussian quadrature rules for the triangle, Int. J. Numer. Methods Eng. 21 (1985) 1129-1148.",
"[29] P. Keast, Moderate-degree tetrahedral quadrature formulas, Comput. Methods Appl. Mech. Eng. 55 (1986) 339-348.",
"[30] A.H. Stroud, Approximate Calculation of Multiple Integrals, Prentice-Hall, Englewood Cliffs, 1971.",
"[31] M. Abramowitz, I.A. Stegun (Eds.), Handbook of Mathematical Functions, Dover, New York, 1964.",
"[32] S.K. Godunov, A difference method for numerical calculation of discontinuous solutions of the equations of hydrodynamics, Mat. Sb. 47 (1959) 271-306.",
"[33] A. Harten, High resolution schemes for hyperbolic conservation laws, J. Comput. Phys. 49 (1983) 357-393.",
"[34] P.K. Sweby, High resolution schemes using flux limiters for hyperbolic conservation laws, SIAM J. Numer. Anal. 21 (1984) 995-1011.",
"[35] G.-S. Jiang, C.-W. Shu, Efficient implementation of weighted ENO schemes, J. Comput. Phys. 126 (1996) 202-228.",
"[36] J.J. Quirk, A contribution to the great Riemann solver debate, Int. J. Numer. Methods Fluids 18 (1994) 555-574.",
"[37] E.F. Toro, Riemann Solvers and Numerical Methods for Fluid Dynamics: A Practical Introduction, 3rd ed., Springer, Berlin, 2009.",
"[38] B. Einfeldt, On Godunov-type methods for gas dynamics, SIAM J. Numer. Anal. 25 (1988) 294-318.",
"[39] R.J. Spiteri, S.J. Ruuth, A new class of optimal high-order strong-stability-preserving time discretization methods, SIAM J. Numer. Anal. 40 (2002) 469-491.",
"[40] S. Diot, R. Loubere, S. Clain, The Multidimensional Optimal Order Detection method in the three-dimensional case: very high-order finite volume method for hyperbolic systems, Int. J. Numer. Methods Fluids 73 (2013) 362-392.",
"[41] M. Dumbser, O. Zanotti, R. Loubere, S. Diot, A posteriori subcell limiting of the discontinuous Galerkin finite element method for hyperbolic conservation laws, J. Comput. Phys. 278 (2014) 47-75.",
"[42] X. Zhang, C.-W. Shu, Maximum-principle-satisfying and positivity-preserving high-order schemes for conservation laws: survey and new developments, Proc. R. Soc. A 467 (2011) 2752-2776.",
"[43] B. Perthame, C.-W. Shu, On positivity preserving finite volume schemes for Euler equations, Numer. Math. 73 (1996) 119-130.",
"[44] R.J. LeVeque, Finite Volume Methods for Hyperbolic Problems, Cambridge University Press, Cambridge, 2002.",
"[45] K. Yokoi, Efficient implementation of THINC scheme: A simple and practical smoothed VOF algorithm, J. Comput. Phys. 226 (2007) 1985-2002.",
"[46] F. Xiao, S. Ii, C. Chen, Revisit to the THINC scheme: A simple algebraic VOF algorithm, J. Comput. Phys. 230 (2011) 7086-7092.",
"[47] X. Deng, Z.-H. Jiang, F. Xiao, C. Yan, Implicit large eddy simulation of compressible turbulence flow with PnTm-BVD scheme, Appl. Math. Model. 77 (2020) 17-31.",
"[48] S. Tann, X. Deng, Y. Shimizu, R. Loubere, F. Xiao, Solution property preserving reconstruction for finite volume scheme: a BVD+MOOD framework, Int. J. Numer. Methods Fluids 92 (2020) 603-634.",
"[49] S.T. Zalesak, Fully multidimensional flux-corrected transport algorithms for fluids, J. Comput. Phys. 31 (1979) 335-362.",
"[50] A. Kurganov, E. Tadmor, Solution of two-dimensional Riemann problems for gas dynamics without Riemann problem solvers, Numer. Methods Partial Differ. Equ. 18 (2002) 584-608."
].forEach(r => C.push(refP(r)));

const doc = new Document({
  styles: { default: { document: { run: { font: FONT, size: SZ } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal",
        run: { size: 22, bold: true, font: FONT }, paragraph: { spacing: { before: 280, after: 160 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal",
        run: { size: 20, bold: true, italics: true, font: FONT }, paragraph: { spacing: { before: 220, after: 120 }, outlineLevel: 1 } } ] },
  sections: [{ properties: { page: { size: { width: 12240, height: 15840 },
    margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } }, children: C }] });

Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2] || "paper2_draft.docx", b); console.log("paper2 expanded written"); });
