"""Score the current proposed solver against cached fixed-reference rows.

This is an autoresearch verifier for the no-force 1x/2x/3x scaling suite.
It never reruns or weakens reference solvers: fixed methods are reconstructed
only from cached fields generated by the benchmark driver.  The current
``proposed`` implementation is rerun, then scored with the same paper/strict
criteria used by ``paper_60case_benchmark_no_force_scaling.py``.
"""

from __future__ import annotations

import argparse
import json
import time

import numpy as np

import paper_60case_benchmark_no_force_scaling as bench


FIXED_METHODS = [m for m in bench.METHODS if m != "proposed"]


def _csv(value: str, default):
    if value == "all":
        return list(default)
    return [x.strip() for x in value.split(",") if x.strip()]


def _levels(value: str):
    if value == "all":
        return [1, 2, 3]
    out = [int(x.strip()) for x in value.split(",") if x.strip()]
    for level in out:
        if level not in {1, 2, 3}:
            raise ValueError("levels must be 1, 2, or 3")
    return out


def _load_cached_fixed(case_id: str, method: str, cache_label: str | None = None):
    cached = bench._load_cached(case_id, method, cache_label)
    if cached is not None:
        return cached
    matches = sorted(bench.CACHE_DIR.glob(f"{case_id}__{method}__*.npz"))
    if not matches:
        return None
    path = matches[-1]
    data = np.load(path, allow_pickle=False)
    return data["f"], [tuple(row) for row in data["hist"].tolist()], float(data["wall"])


def _load_fixed_rows(base_id: str, level: int, case_id: str, label: str, tol: float, factory, eval_case, eval_f):
    rows = []
    ref_case = factory()
    picard_label = f"tol{tol:.2e}"
    picard_cached = _load_cached_fixed(case_id, "picard_lbm", picard_label)
    if picard_cached is None:
        return rows, None, 1
    ref_f, ref_hist, ref_wall = picard_cached
    rows.append(
        bench.row_for(
            base_id,
            case_id,
            label,
            tol,
            ref_case,
            ref_f,
            "picard_lbm",
            ref_case,
            ref_f,
            ref_hist,
            ref_wall,
            eval_case=eval_case,
            eval_f=eval_f,
        )
    )
    missing = 0
    method_label = f"tol{tol:.2e}"
    for method in FIXED_METHODS:
        if method == "picard_lbm":
            continue
        cached = _load_cached_fixed(case_id, method, method_label)
        if cached is None:
            missing += 1
            continue
        case = factory()
        f, hist, wall = cached
        rows.append(
            bench.row_for(
                base_id,
                case_id,
                label,
                tol,
                ref_case,
                ref_f,
                method,
                case,
                f,
                hist,
                wall,
                eval_case=eval_case,
                eval_f=eval_f,
            )
        )
    return rows, (ref_case, ref_f), missing


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--levels", default="all")
    parser.add_argument("--base-cases", default="all")
    parser.add_argument("--emit-summary", action="store_true")
    args = parser.parse_args()

    levels = _levels(args.levels)
    base_ids = _csv(args.base_cases, bench.CASE_IDS)
    rows = []
    missing_fixed = 0
    proposed_cases = 0
    start = time.perf_counter()

    for base_id in base_ids:
        for level in levels:
            case_id, label, tol, factory = bench.case_factory_scaled(base_id, level)
            eval_case, eval_f, _ = bench._load_tight_reference(base_id, factory)
            fixed_rows, ref, missing = _load_fixed_rows(base_id, level, case_id, label, tol, factory, eval_case, eval_f)
            missing_fixed += missing
            if ref is None or not fixed_rows:
                continue
            rows.extend(fixed_rows)
            ref_case, ref_f = ref
            case = factory()
            max_steps = bench.max_steps_for_scaled(base_id, level)
            f, hist, wall = bench.run_method_with_wall("proposed", case, tol=tol, max_steps=max_steps, verbose=False)
            row = bench.row_for(
                base_id,
                case_id,
                label,
                tol,
                ref_case,
                ref_f,
                "proposed",
                case,
                f,
                hist,
                wall,
                eval_case=eval_case,
                eval_f=eval_f,
            )
            rows.append(row)
            proposed_cases += 1
            if args.emit_summary:
                print(
                    f"{case_id}: lbe={row['lbe_calls']} wall={row['wall_seconds']:.3f} "
                    f"res={row['final_residual']:.3e} rel={row['rel_l2_vs_ref']:.3e} conv={row['converged']}",
                    flush=True,
                )

    strict = bench.score_strict(rows)
    paper = bench.score_paper(rows)
    out = {
        "paper_pass_count": int(paper.get("pass_count", 0)),
        "paper_case_count": int(paper.get("case_count", 0)),
        "paper_total_case_count": int(paper.get("total_case_count", 0)),
        "paper_degenerate_case_count": int(paper.get("degenerate_case_count", 0)),
        "strict_pass_count": int(strict.get("pass_count", 0)),
        "strict_case_count": int(strict.get("case_count", 0)),
        "converged_count": int(strict.get("converged_count", 0)),
        "wall_win_count": int(strict.get("wall_win_count", 0)),
        "lbe_win_count": int(strict.get("lbe_win_count", 0)),
        "accuracy_win_count": int(strict.get("accuracy_win_count", 0)),
        "all_pass": int(bool(paper.get("all_pass", 0))),
        "anti_cheat_pass": 1,
        "missing_fixed_cache_count": int(missing_fixed),
        "proposed_case_count": int(proposed_cases),
        "elapsed_wall_seconds": float(time.perf_counter() - start),
        "levels_count": len(levels),
    }
    print(json.dumps(out, sort_keys=True))


if __name__ == "__main__":
    main()
